# autogenerated by ssc-gen. DO NOT EDIT
"""Aniliberty REST API client (https://aniliberty.top/api/v1).

API docs: https://aniliberty.top/api/docs/v1
No authentication required."""

from dataclasses import dataclass
from typing import TypedDict, Optional, Any, List, Union, Literal, Mapping

import httpx
from .sscgen_runtime import (
    Ok,
    Err,
    UnknownErr,
    TransportErr,
    ssc_parse_response,
)

TypedValueJson = TypedDict(
    "TypedValueJson",
    {
        "value": Optional[str],
        "description": Optional[str],
    },
)
ReleaseNameJson = TypedDict(
    "ReleaseNameJson",
    {
        "main": str,
        "english": Optional[str],
        "alternative": Optional[str],
    },
)
ImageJson = TypedDict(
    "ImageJson",
    {
        "preview": str,
        "thumbnail": str,
    },
)
ImageOptimizedJson = TypedDict(
    "ImageOptimizedJson",
    {
        "preview": str,
        "thumbnail": str,
        "optimized": ImageJson,
    },
)
PosterImageJson = TypedDict(
    "PosterImageJson",
    {
        "src": str,
        "preview": str,
        "thumbnail": str,
    },
)
PosterJson = TypedDict(
    "PosterJson",
    {
        "src": str,
        "preview": str,
        "thumbnail": str,
        "optimized": PosterImageJson,
    },
)
AgeRatingJson = TypedDict(
    "AgeRatingJson",
    {
        "value": str,
        "label": str,
        "description": str,
        "is_adult": bool,
    },
)
PublishDayJson = TypedDict(
    "PublishDayJson",
    {
        "value": Optional[int],
        "description": Optional[str],
    },
)
EpisodeSkipJson = TypedDict(
    "EpisodeSkipJson",
    {
        "start": Optional[int],
        "stop": Optional[int],
    },
)
GenreJson = TypedDict(
    "GenreJson",
    {
        "id": int,
        "name": str,
        "image": ImageOptimizedJson,
        "total_releases": int,
    },
)
EpisodeJson = TypedDict(
    "EpisodeJson",
    {
        "id": str,
        "name": Optional[str],
        "ordinal": float,
        "opening": EpisodeSkipJson,
        "ending": EpisodeSkipJson,
        "preview": PosterJson,
        "hls_480": str,
        "hls_720": str,
        "hls_1080": Optional[str],
        "duration": int,
        "sort_order": int,
        "release_id": int,
        "name_english": Optional[str],
        "updated_at": str,
        "rutube_id": Optional[str],
        "youtube_id": Optional[str],
    },
)
PaginationLinksJson = TypedDict(
    "PaginationLinksJson",
    {
        "previous": Optional[str],
        "next": Optional[str],
    },
)
PaginationJson = TypedDict(
    "PaginationJson",
    {
        "total": int,
        "count": int,
        "per_page": int,
        "current_page": int,
        "total_pages": int,
        "links": PaginationLinksJson,
    },
)
MetaJson = TypedDict(
    "MetaJson",
    {
        "pagination": PaginationJson,
    },
)
ReleaseSearchJson = TypedDict(
    "ReleaseSearchJson",
    {
        "id": int,
        "type": TypedValueJson,
        "year": Optional[int],
        "name": ReleaseNameJson,
        "alias": str,
        "season": TypedValueJson,
        "poster": PosterJson,
        "publish_day": PublishDayJson,
        "fresh_at": str,
        "created_at": str,
        "updated_at": str,
        "is_ongoing": bool,
        "age_rating": AgeRatingJson,
        "description": str,
        "notification": Optional[str],
        "episodes_total": int,
        "external_player": Optional[str],
        "is_in_production": bool,
        "is_blocked_by_geo": bool,
        "is_blocked_by_copyrights": bool,
        "added_in_users_favorites": int,
        "average_duration_of_episode": int,
        "added_in_planned_collection": int,
        "added_in_watched_collection": int,
        "added_in_watching_collection": int,
        "added_in_postponed_collection": int,
        "added_in_abandoned_collection": int,
    },
)
CatalogReleaseJson = TypedDict(
    "CatalogReleaseJson",
    {
        "id": int,
        "type": TypedValueJson,
        "year": Optional[int],
        "name": ReleaseNameJson,
        "alias": str,
        "season": TypedValueJson,
        "poster": PosterJson,
        "publish_day": PublishDayJson,
        "fresh_at": str,
        "created_at": str,
        "updated_at": str,
        "is_ongoing": bool,
        "age_rating": AgeRatingJson,
        "description": str,
        "notification": Optional[str],
        "episodes_total": int,
        "external_player": Optional[str],
        "is_in_production": bool,
        "is_blocked_by_geo": bool,
        "is_blocked_by_copyrights": bool,
        "added_in_users_favorites": int,
        "average_duration_of_episode": int,
        "added_in_planned_collection": int,
        "added_in_watched_collection": int,
        "added_in_watching_collection": int,
        "added_in_postponed_collection": int,
        "added_in_abandoned_collection": int,
        "genres": List[GenreJson],
    },
)
CatalogReleasesResponseJson = TypedDict(
    "CatalogReleasesResponseJson",
    {
        "data": List[CatalogReleaseJson],
        "meta": MetaJson,
    },
)
MemberRoleJson = TypedDict(
    "MemberRoleJson",
    {
        "value": str,
        "description": str,
    },
)
MemberUserJson = TypedDict(
    "MemberUserJson",
    {
        "id": int,
        "avatar": ImageOptimizedJson,
    },
)
MemberJson = TypedDict(
    "MemberJson",
    {
        "id": str,
        "role": MemberRoleJson,
        "nickname": str,
        "user": MemberUserJson,
    },
)
SponsorJson = TypedDict(
    "SponsorJson",
    {
        "id": str,
        "title": str,
        "description": str,
        "url_title": str,
        "url": str,
    },
)
ReleaseDetailJson = TypedDict(
    "ReleaseDetailJson",
    {
        "id": int,
        "type": TypedValueJson,
        "year": Optional[int],
        "name": ReleaseNameJson,
        "alias": str,
        "season": TypedValueJson,
        "poster": PosterJson,
        "publish_day": PublishDayJson,
        "fresh_at": str,
        "created_at": str,
        "updated_at": str,
        "is_ongoing": bool,
        "age_rating": AgeRatingJson,
        "description": str,
        "notification": Optional[str],
        "episodes_total": int,
        "external_player": Optional[str],
        "is_in_production": bool,
        "is_blocked_by_geo": bool,
        "is_blocked_by_copyrights": bool,
        "added_in_users_favorites": int,
        "average_duration_of_episode": int,
        "added_in_planned_collection": int,
        "added_in_watched_collection": int,
        "added_in_watching_collection": int,
        "added_in_postponed_collection": int,
        "added_in_abandoned_collection": int,
        "genres": List[GenreJson],
        "members": List[MemberJson],
        "episodes": List[EpisodeJson],
        "sponsors": List[SponsorJson],
    },
)
EpisodeReleaseJson = TypedDict(
    "EpisodeReleaseJson",
    {
        "id": int,
        "type": TypedValueJson,
        "year": Optional[int],
        "name": ReleaseNameJson,
        "alias": str,
        "season": TypedValueJson,
        "poster": PosterJson,
        "publish_day": PublishDayJson,
        "fresh_at": str,
        "created_at": str,
        "updated_at": str,
        "is_ongoing": bool,
        "age_rating": AgeRatingJson,
        "description": str,
        "notification": Optional[str],
        "episodes_total": int,
        "external_player": Optional[str],
        "is_in_production": bool,
        "is_blocked_by_geo": bool,
        "is_blocked_by_copyrights": bool,
        "added_in_users_favorites": int,
        "average_duration_of_episode": int,
        "added_in_planned_collection": int,
        "added_in_watched_collection": int,
        "added_in_watching_collection": int,
        "added_in_postponed_collection": int,
        "added_in_abandoned_collection": int,
        "episodes": List[EpisodeJson],
    },
)
EpisodeDetailJson = TypedDict(
    "EpisodeDetailJson",
    {
        "id": str,
        "name": Optional[str],
        "ordinal": float,
        "opening": EpisodeSkipJson,
        "ending": EpisodeSkipJson,
        "preview": PosterJson,
        "hls_480": str,
        "hls_720": str,
        "hls_1080": Optional[str],
        "duration": int,
        "sort_order": int,
        "release_id": int,
        "name_english": Optional[str],
        "updated_at": str,
        "rutube_id": Optional[str],
        "youtube_id": Optional[str],
        "release": EpisodeReleaseJson,
    },
)
ReleaseEpisodesJson = TypedDict(
    "ReleaseEpisodesJson",
    {
        "id": int,
        "episodes": List[EpisodeJson],
    },
)
AppStatusRequestJson = TypedDict(
    "AppStatusRequestJson",
    {
        "ip": str,
        "country": str,
        "iso_code": str,
        "timezone": str,
    },
)
AppStatusJson = TypedDict(
    "AppStatusJson",
    {
        "request": AppStatusRequestJson,
        "is_alive": bool,
        "available_api_endpoints": List[str],
    },
)
ApiErrorJson = TypedDict(
    "ApiErrorJson",
    {
        "message": str,
    },
)


@dataclass(frozen=True)
class AnilibertyApiErr404(Err[ApiErrorJson]):
    status: Literal[404] = 404


SearchCatalogResult = Union[Ok[CatalogReleasesResponseJson], AnilibertyApiErr404, UnknownErr, TransportErr]
OngoingCatalogResult = Union[Ok[CatalogReleasesResponseJson], AnilibertyApiErr404, UnknownErr, TransportErr]
SearchResult = Union[Ok[ReleaseSearchJson], AnilibertyApiErr404, UnknownErr, TransportErr]
GetReleaseResult = Union[Ok[ReleaseDetailJson], AnilibertyApiErr404, UnknownErr, TransportErr]
GetReleaseEpisodesResult = Union[Ok[ReleaseEpisodesJson], AnilibertyApiErr404, UnknownErr, TransportErr]
GetEpisodeResult = Union[Ok[EpisodeDetailJson], AnilibertyApiErr404, UnknownErr, TransportErr]
AppStatusResult = Union[Ok[AppStatusJson], AnilibertyApiErr404, UnknownErr, TransportErr]


class AnilibertyApi:
    @staticmethod
    def ssc_dispatch_err(
        _status: int, _headers: Mapping[str, str], _body: Any
    ) -> Union[AnilibertyApiErr404, UnknownErr, None]:
        if 200 <= _status < 300:
            return None
        if _status == 404:
            return AnilibertyApiErr404(headers=_headers, value=_body)
        return UnknownErr(status=_status, headers=_headers, value=_body)

    """
    Aniliberty API client.
    """

    @classmethod
    def search_catalog(
        cls, client: httpx.Client, *, search: str, page: Optional[int] = None, limit: Optional[int] = None
    ) -> SearchCatalogResult:
        """Search releases via catalog endpoint with filter."""
        _params: dict = {}
        _params["f[search]"] = search
        if page is not None:
            _params["page"] = page
        if limit is not None:
            _params["limit"] = limit
        try:
            _resp = client.request(
                "GET",
                "https://aniliberty.top/api/v1/anime/catalog/releases",
                headers={"Accept": "application/json"},
                params=_params,
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_search_catalog(
        cls, client: httpx.AsyncClient, *, search: str, page: Optional[int] = None, limit: Optional[int] = None
    ) -> SearchCatalogResult:
        """Search releases via catalog endpoint with filter."""
        _params: dict = {}
        _params["f[search]"] = search
        if page is not None:
            _params["page"] = page
        if limit is not None:
            _params["limit"] = limit
        try:
            _resp = await client.request(
                "GET",
                "https://aniliberty.top/api/v1/anime/catalog/releases",
                headers={"Accept": "application/json"},
                params=_params,
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    def ongoing_catalog(
        cls, client: httpx.Client, *, page: Optional[int] = None, limit: Optional[int] = None
    ) -> OngoingCatalogResult:
        """List ongoing/newest releases with pagination."""
        _params: dict = {}
        if page is not None:
            _params["page"] = page
        if limit is not None:
            _params["limit"] = limit
        try:
            _resp = client.request(
                "GET",
                "https://aniliberty.top/api/v1/anime/catalog/releases",
                headers={"Accept": "application/json"},
                params=_params,
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_ongoing_catalog(
        cls, client: httpx.AsyncClient, *, page: Optional[int] = None, limit: Optional[int] = None
    ) -> OngoingCatalogResult:
        """List ongoing/newest releases with pagination."""
        _params: dict = {}
        if page is not None:
            _params["page"] = page
        if limit is not None:
            _params["limit"] = limit
        try:
            _resp = await client.request(
                "GET",
                "https://aniliberty.top/api/v1/anime/catalog/releases",
                headers={"Accept": "application/json"},
                params=_params,
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    def search(cls, client: httpx.Client, *, query: str) -> SearchResult:
        """Search releases via dedicated search endpoint. Returns bare array."""
        try:
            _resp = client.request(
                "GET",
                "https://aniliberty.top/api/v1/app/search/releases",
                headers={"Accept": "application/json"},
                params={"query": query},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_search(cls, client: httpx.AsyncClient, *, query: str) -> SearchResult:
        """Search releases via dedicated search endpoint. Returns bare array."""
        try:
            _resp = await client.request(
                "GET",
                "https://aniliberty.top/api/v1/app/search/releases",
                headers={"Accept": "application/json"},
                params={"query": query},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    def get_release(cls, client: httpx.Client, *, id: int) -> GetReleaseResult:
        """Get full release detail with episodes, members, genres."""
        try:
            _resp = client.request(
                "GET",
                f"https://aniliberty.top/api/v1/anime/releases/{id}",
                headers={"Accept": "application/json"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_get_release(cls, client: httpx.AsyncClient, *, id: int) -> GetReleaseResult:
        """Get full release detail with episodes, members, genres."""
        try:
            _resp = await client.request(
                "GET",
                f"https://aniliberty.top/api/v1/anime/releases/{id}",
                headers={"Accept": "application/json"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    def get_release_episodes(cls, client: httpx.Client, *, id: int) -> GetReleaseEpisodesResult:
        """Get episodes for a release (sparse fieldset)."""
        try:
            _resp = client.request(
                "GET",
                f"https://aniliberty.top/api/v1/anime/releases/{id}",
                headers={"Accept": "application/json"},
                params={"include": "id,episodes"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_get_release_episodes(cls, client: httpx.AsyncClient, *, id: int) -> GetReleaseEpisodesResult:
        """Get episodes for a release (sparse fieldset)."""
        try:
            _resp = await client.request(
                "GET",
                f"https://aniliberty.top/api/v1/anime/releases/{id}",
                headers={"Accept": "application/json"},
                params={"include": "id,episodes"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    def get_episode(cls, client: httpx.Client, *, episode_id: str) -> GetEpisodeResult:
        """Get single episode by id with nested release."""
        try:
            _resp = client.request(
                "GET",
                f"https://aniliberty.top/api/v1/anime/releases/episodes/{episode_id}",
                headers={"Accept": "application/json"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_get_episode(cls, client: httpx.AsyncClient, *, episode_id: str) -> GetEpisodeResult:
        """Get single episode by id with nested release."""
        try:
            _resp = await client.request(
                "GET",
                f"https://aniliberty.top/api/v1/anime/releases/episodes/{episode_id}",
                headers={"Accept": "application/json"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    def app_status(cls, client: httpx.Client) -> AppStatusResult:
        """Check API availability."""
        try:
            _resp = client.request(
                "GET",
                "https://aniliberty.top/api/v1/app/status",
                headers={"Accept": "application/json"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_app_status(cls, client: httpx.AsyncClient) -> AppStatusResult:
        """Check API availability."""
        try:
            _resp = await client.request(
                "GET",
                "https://aniliberty.top/api/v1/app/status",
                headers={"Accept": "application/json"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)
