# autogenerated by ssc-gen. DO NOT EDIT
from lxml import html
from lxml.html import HtmlElement
import sys
from typing import Any, Dict, List, TypedDict, Union
import re
import json
import httpx

if sys.version_info >= (3, 11):
    from typing import NotRequired
else:
    from typing_extensions import NotRequired
from .sscgen_runtime import FALLBACK_HTML_STR

from .sscgen_runtime import std_re_search

AggregateRatingJson = TypedDict(
    "AggregateRatingJson",
    {
        "@type": str,
        "ratingCount": NotRequired[int],
        "bestRating": NotRequired[int],
        "ratingValue": NotRequired[float],
        "worstRating": NotRequired[int],
    },
)
DirectorJson = TypedDict(
    "DirectorJson",
    {
        "@type": str,
        "url": str,
        "name": str,
    },
)
ActorJson = TypedDict(
    "ActorJson",
    {
        "@type": str,
        "url": str,
        "name": str,
    },
)
CreatorJson = TypedDict(
    "CreatorJson",
    {
        "@type": str,
        "name": str,
    },
)
ContentJson = TypedDict(
    "ContentJson",
    {
        "@context": str,
        "@type": str,
        "url": str,
        "name": str,
        "alternateName": str,
        "image": str,
        "description": str,
        "genre": List[str],
        "contentRating": str,
        "datePublished": str,
        "keywords": str,
        "creator": List[CreatorJson],
        "aggregateRating": AggregateRatingJson,
        "numberOfEpisodes": NotRequired[int],
    },
)
PageOngoingType = TypedDict(
    "PageOngoingType",
    {
        "url_path": str,
        "title": str,
        "thumbnail": str,
        "episode": str,
        "dub": str,
    },
)
PageSearchType = TypedDict(
    "PageSearchType",
    {
        "title": str,
        "thumbnail": str,
        "url_path": str,
    },
)
PageAnimeType = TypedDict(
    "PageAnimeType",
    {
        "title": str,
        "description": str,
        "thumbnail": str,
        "id": str,
        "raw_json": ContentJson,
    },
)
EpisodesType = TypedDict(
    "EpisodesType",
    {
        "num": int,
        "title": str,
        "type": str,
        "released": str,
        "id": str,
    },
)
EpisodeVideosType = TypedDict(
    "EpisodeVideosType",
    {
        "player": str,
        "data_provider": str,
        "data_provide_dubbing": str,
    },
)
DubbersType = Dict[str, str]
PageEpisodeType = TypedDict(
    "PageEpisodeType",
    {
        "dubbers": DubbersType,
        "episodes": List[EpisodesType],
        "videos": List[EpisodeVideosType],
    },
)
SourceVideoViewType = TypedDict(
    "SourceVideoViewType",
    {
        "title": str,
        "url": str,
        "data_provider": str,
        "data_provide_dubbing": str,
        "data_translation_title": str,
    },
)
PageSourceType = TypedDict(
    "PageSourceType",
    {
        "dubbers": DubbersType,
        "videos": List[SourceVideoViewType],
    },
)


class PageOngoing:
    "Get all available ongoings from the main page\n\nGET https://animego.me\n\nNOTE: animego can change the domain, so only the path is returned.\nTo get the real url, extract the value using the selector 'link[rel=\"canonical\"]::attr(href)'"

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        else:
            self._doc = document

    def _split_doc(self, v: HtmlElement) -> List[HtmlElement]:
        v1 = v.cssselect(".updates-body > div.d-grid > a.aw-item")
        return v1

    @classmethod
    def fetch(cls, client: httpx.Client, **kwargs: Any) -> "PageOngoing":
        _kw: Dict[str, Any] = {}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        _resp = client.request(
            "GET",
            "https://animego.me",
            **_kw,
        )
        _resp.raise_for_status()
        _body = _resp.text
        return cls(_body)

    @classmethod
    async def async_fetch(cls, client: httpx.AsyncClient, **kwargs: Any) -> "PageOngoing":
        _kw: Dict[str, Any] = {}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        _resp = await client.request(
            "GET",
            "https://animego.me",
            **_kw,
        )
        _resp.raise_for_status()
        _body = _resp.text
        return cls(_body)

    def _parse_url_path(self, v: HtmlElement) -> str:
        v1 = v.get("href", "")
        return v1

    def _parse_title(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".image__img")[0]
        v2 = v1.get("alt", "")
        return v2

    def _parse_thumbnail(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".image__img")[0]
        v2 = v1.get("src", "")
        return v2

    def _parse_episode(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".aw-meta")[0]
        v2 = v1.text_content()
        v3 = re.sub("\\d+-", "", v2)
        v4 = std_re_search(
            "\\s(\\d+)\\s", v3, "animego_parser.kdl:41:9 re-match failed at PageOngoing.episode pattern=\\s(\\d+)\\s"
        )
        return v4

    def _parse_dub(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".aw-meta")[0]
        v2 = v1.text_content()
        v3 = std_re_search(
            "(\\w+)\\s+—", v2, "animego_parser.kdl:43:33 re-match failed at PageOngoing.dub pattern=(\\w+)\\s+—"
        )
        return v3

    def parse(self) -> List[PageOngoingType]:
        return [
            {
                "url_path": self._parse_url_path(i),
                "title": self._parse_title(i),
                "thumbnail": self._parse_thumbnail(i),
                "episode": self._parse_episode(i),
                "dub": self._parse_dub(i),
            }
            for i in self._split_doc(self._doc)
        ]


class PageSearch:
    "Get all search results by query\n\nUSAGE:\n\n    GET https://animego.me/search/anime\n    q={QUERY}\n\nEXAMPLE:\n\n    GET https://animego.me/search/anime?q=LAIN"

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        else:
            self._doc = document

    def _split_doc(self, v: HtmlElement) -> List[HtmlElement]:
        v1 = v.cssselect(".grid.ani-list .ani-grid__item")
        return v1

    @classmethod
    def fetch(cls, client: httpx.Client, *, query: str, **kwargs: Any) -> "PageSearch":
        _kw: Dict[str, Any] = {}
        _kw["params"] = {"q": query}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        _resp = client.request(
            "GET",
            "https://animego.me/search/anime",
            **_kw,
        )
        _resp.raise_for_status()
        _body = _resp.text
        return cls(_body)

    @classmethod
    async def async_fetch(cls, client: httpx.AsyncClient, *, query: str, **kwargs: Any) -> "PageSearch":
        _kw: Dict[str, Any] = {}
        _kw["params"] = {"q": query}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        _resp = await client.request(
            "GET",
            "https://animego.me/search/anime",
            **_kw,
        )
        _resp.raise_for_status()
        _body = _resp.text
        return cls(_body)

    def _parse_title(self, v: HtmlElement) -> str:
        v1 = v.cssselect("a.ani-grid__item-picture img")[0]
        v2 = v1.get("alt", "")
        return v2

    def _parse_thumbnail(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".image__img")[0]
        v2 = v1.get("src", "")
        return v2

    def _parse_url_path(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".ani-grid__item-title a")[0]
        v2 = v1.get("href", "")
        return v2

    def parse(self) -> List[PageSearchType]:
        return [
            {
                "title": self._parse_title(i),
                "thumbnail": self._parse_thumbnail(i),
                "url_path": self._parse_url_path(i),
            }
            for i in self._split_doc(self._doc)
        ]


class PageAnime:
    "Anime page information. anime path contains in SearchView.url or Ongoing.url\n\n- id needed for next API requests\n- raw_json used for extract extra metadata (unescape required)\n\nUSAGE:\n\n    GET https://animego.me/anime/<ANIME_PATH>\n\nEXAMPLE:\n\n    GET https://animego.me/anime/eksperimenty-leyn-1114\n\n\nISSUES:\n    If blocked, you can try skip extract anime metadata and send api request:\n\n    id contains in url:\n        - id=1114 for https://animego.me/anime/eksperimenty-leyn-1114\n        - id=2589 for https://animego.me/anime/chelovek-muskul-2589\n\n    GET 'https://animego.me/anime/{id}/player?_allow=true'"

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        else:
            self._doc = document

    @classmethod
    def fetch(cls, client: httpx.Client, *, slug: str, **kwargs: Any) -> "PageAnime":
        _kw: Dict[str, Any] = {}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        _resp = client.request(
            "GET",
            f"https://animego.me/anime/{slug}",
            **_kw,
        )
        _resp.raise_for_status()
        _body = _resp.text
        return cls(_body)

    @classmethod
    async def async_fetch(cls, client: httpx.AsyncClient, *, slug: str, **kwargs: Any) -> "PageAnime":
        _kw: Dict[str, Any] = {}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        _resp = await client.request(
            "GET",
            f"https://animego.me/anime/{slug}",
            **_kw,
        )
        _resp.raise_for_status()
        _body = _resp.text
        return cls(_body)

    def _parse_title(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".entity__title h1")[0]
        v2 = v1.text_content()
        return v2

    def _parse_description(self, v: HtmlElement) -> str:
        try:
            v1 = v.cssselect(".description")
            v2 = [i.text_content() for i in v1]
            v3 = "".join(v2)
            v4 = v3.strip()
            return v4
        except Exception:
            return ""

    def _parse_thumbnail(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".d-sm-flex .image__picture img.image__img")[0]
        v2 = v1.get("src", "")
        return v2

    def _parse_id(self, v: HtmlElement) -> str:
        v1 = v.cssselect('link[rel="canonical"]')[0]
        v2 = v1.get("href", "")
        v3 = std_re_search(
            "-(.?\\d{2,})", v2, "animego_parser.kdl:158:9 re-match failed at PageAnime.id pattern=-(.?\\d{2,})"
        )
        return v3

    def _parse_raw_json(self, v: HtmlElement) -> ContentJson:
        v1 = v.cssselect("script[type='application/ld+json']")[0]
        v2 = v1.text_content()
        v3 = json.loads(v2)
        return v3

    def parse(self) -> PageAnimeType:
        return {
            "title": self._parse_title(self._doc),
            "description": self._parse_description(self._doc),
            "thumbnail": self._parse_thumbnail(self._doc),
            "id": self._parse_id(self._doc),
            "raw_json": self._parse_raw_json(self._doc),
        }


class Episodes:
    'episodes signature example (exclude in film)\n```\n<div class="scroll-snap-slider d-none d-lg-flex">\n    <div class="scroll-snap-slide player-video-bar__item user-select-none px-1"\n        data-episode-number="1" data-episode-type="1"\n        data-episode-title="Elaina, the Apprentice Witch" data-episode-released="2 октября 2020"\n        data-episode-description="" data-episode="21516">\n        ...\n```'

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        else:
            self._doc = document

    def _split_doc(self, v: HtmlElement) -> List[HtmlElement]:
        v1 = v.cssselect(".player-video-bar__item")
        return v1

    def _parse_num(self, v: HtmlElement) -> int:
        v1 = v.get("data-episode-number", "")
        v2 = re.sub("\\D", "", v1)
        v3 = int(v2)
        return v3

    def _parse_title(self, v: HtmlElement) -> str:
        v1 = v.get("data-episode-title", "")
        return v1

    def _parse_type(self, v: HtmlElement) -> str:
        v1 = v.get("data-episode-type", "")
        return v1

    def _parse_released(self, v: HtmlElement) -> str:
        v1 = v.get("data-episode-released", "")
        return v1

    def _parse_id(self, v: HtmlElement) -> str:
        v1 = v.get("data-episode", "")
        return v1

    def parse(self) -> List[EpisodesType]:
        return [
            {
                "num": self._parse_num(i),
                "title": self._parse_title(i),
                "type": self._parse_type(i),
                "released": self._parse_released(i),
                "id": self._parse_id(i),
            }
            for i in self._split_doc(self._doc)
        ]


class EpisodeVideos:
    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        else:
            self._doc = document

    def _split_doc(self, v: HtmlElement) -> List[HtmlElement]:
        v1 = v.cssselect("button[data-player]")
        return v1

    def _parse_player(self, v: HtmlElement) -> str:
        v1 = v.get("data-player", "")
        v2 = re.sub("^https?", "", v1)
        v3 = "https:{}".format(v2)
        return v3

    def _parse_data_provider(self, v: HtmlElement) -> str:
        v1 = v.get("data-provider", "")
        return v1

    def _parse_data_provide_dubbing(self, v: HtmlElement) -> str:
        v1 = v.get("data-ptranslation", "")
        v2 = v1.strip()
        return v2

    def parse(self) -> List[EpisodeVideosType]:
        return [
            {
                "player": self._parse_player(i),
                "data_provider": self._parse_data_provider(i),
                "data_provide_dubbing": self._parse_data_provide_dubbing(i),
            }
            for i in self._split_doc(self._doc)
        ]


class Dubbers:
    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        else:
            self._doc = document

    def _split_doc(self, v: HtmlElement) -> List[HtmlElement]:
        v1 = v.cssselect("button[data-translation]")
        return v1

    def _parse_key(self, v: HtmlElement) -> str:
        v1 = v.get("data-translation", "")
        return v1

    def _parse_value(self, v: HtmlElement) -> str:
        v1 = v.cssselect("span")[0]
        v2 = v1.text_content()
        v3 = v2.strip()
        return v3

    def parse(self) -> DubbersType:
        return {self._parse_key(i): self._parse_value(i) for i in self._split_doc(self._doc)}


class PageEpisode:
    "Representation episodes\n\nNOTE:\n    film pages does not exist select[name=\"series\"] element.\n    check is_film flag. if true - get from videos key elements else episodes\n\nPrepare:\n  1. get id from Anime object\n  2. GET 'https://animego.me/player/{Anime.id}'\n  3. extract html from json by ['data']['content'] key\n  4. OPTIONAL: unescape HTML\n\nEXAMPLE:\n    GET https://animego.me/player/1114"

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        else:
            self._doc = document

    @classmethod
    def fetch(cls, client: httpx.Client, *, anime_id: str, **kwargs: Any) -> "PageEpisode":
        _kw: Dict[str, Any] = {}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        _resp = client.request(
            "GET",
            f"https://animego.me/player/{anime_id}",
            **_kw,
        )
        _resp.raise_for_status()
        _data = _resp.json()
        _body = _data["data"]["content"]
        return cls(_body)

    @classmethod
    async def async_fetch(cls, client: httpx.AsyncClient, *, anime_id: str, **kwargs: Any) -> "PageEpisode":
        _kw: Dict[str, Any] = {}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        _resp = await client.request(
            "GET",
            f"https://animego.me/player/{anime_id}",
            **_kw,
        )
        _resp.raise_for_status()
        _data = _resp.json()
        _body = _data["data"]["content"]
        return cls(_body)

    def _parse_dubbers(self, v: HtmlElement) -> DubbersType:
        v1 = Dubbers(v).parse()
        return v1

    def _parse_episodes(self, v: HtmlElement) -> List[EpisodesType]:
        v1 = Episodes(v).parse()
        return v1

    def _parse_videos(self, v: HtmlElement) -> List[EpisodeVideosType]:
        v1 = EpisodeVideos(v).parse()
        return v1

    def parse(self) -> PageEpisodeType:
        return {
            "dubbers": self._parse_dubbers(self._doc),
            "episodes": self._parse_episodes(self._doc),
            "videos": self._parse_videos(self._doc),
        }


class SourceVideoView:
    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        else:
            self._doc = document

    def _split_doc(self, v: HtmlElement) -> List[HtmlElement]:
        v1 = v.cssselect("button[data-player]")
        return v1

    def _parse_title(self, v: HtmlElement) -> str:
        v1 = v.cssselect("span")[0]
        v2 = v1.text_content()
        return v2

    def _parse_url(self, v: HtmlElement) -> str:
        v1 = v.get("data-player", "")
        v2 = "https:{}".format(v1)
        return v2

    def _parse_data_provider(self, v: HtmlElement) -> str:
        v1 = v.get("data-provider", "")
        return v1

    def _parse_data_provide_dubbing(self, v: HtmlElement) -> str:
        v1 = v.get("data-ptranslation", "")
        v2 = v1.strip()
        return v2

    def _parse_data_translation_title(self, v: HtmlElement) -> str:
        v1 = v.get("data-translation-title", "")
        return v1

    def parse(self) -> List[SourceVideoViewType]:
        return [
            {
                "title": self._parse_title(i),
                "url": self._parse_url(i),
                "data_provider": self._parse_data_provider(i),
                "data_provide_dubbing": self._parse_data_provide_dubbing(i),
                "data_translation_title": self._parse_data_translation_title(i),
            }
            for i in self._split_doc(self._doc)
        ]


class PageSource:
    'representation player urls (episodes only)\n\nPrepare:\n  1. get num and id from Episode\n\n  2.\n\n  GET https://animego.me/player/videos/{Episode.id}\n\n  3. extract html from json by ["data"]["content"] key\n\n  4. OPTIONAL: unescape document\n\nEXAMPLE:\n\n    curl \'https://animego.me/player/videos/42782\''

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        else:
            self._doc = document

    @classmethod
    def fetch(cls, client: httpx.Client, *, episode_id: str, **kwargs: Any) -> "PageSource":
        _kw: Dict[str, Any] = {}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        _resp = client.request(
            "GET",
            f"https://animego.me/player/videos/{episode_id}",
            **_kw,
        )
        _resp.raise_for_status()
        _data = _resp.json()
        _body = _data["data"]["content"]
        return cls(_body)

    @classmethod
    async def async_fetch(cls, client: httpx.AsyncClient, *, episode_id: str, **kwargs: Any) -> "PageSource":
        _kw: Dict[str, Any] = {}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        _resp = await client.request(
            "GET",
            f"https://animego.me/player/videos/{episode_id}",
            **_kw,
        )
        _resp.raise_for_status()
        _data = _resp.json()
        _body = _data["data"]["content"]
        return cls(_body)

    def _parse_dubbers(self, v: HtmlElement) -> DubbersType:
        v1 = Dubbers(v).parse()
        return v1

    def _parse_videos(self, v: HtmlElement) -> List[SourceVideoViewType]:
        v1 = SourceVideoView(v).parse()
        return v1

    def parse(self) -> PageSourceType:
        return {
            "dubbers": self._parse_dubbers(self._doc),
            "videos": self._parse_videos(self._doc),
        }
