# autogenerated by ssc-gen. DO NOT EDIT
"""Animelib.org REST API client (cdnlibs.org backend).
Base URL: https://api.cdnlibs.org/api
Auth: Bearer token optional. Required for animelib player video URLs;
      kodik player works without auth."""

import sys
from dataclasses import dataclass
from typing import TypedDict, Optional, Any, List, Union, Literal, Mapping

if sys.version_info >= (3, 11):
    from typing import NotRequired
else:
    from typing_extensions import NotRequired
import httpx
from .sscgen_runtime import (
    Ok,
    Err,
    UnknownErr,
    TransportErr,
    ssc_parse_response,
)

CoverJson = TypedDict(
    "CoverJson",
    {
        "filename": str,
        "thumbnail": str,
        "default": str,
        "md": str,
    },
)
BackgroundJson = TypedDict(
    "BackgroundJson",
    {
        "filename": str,
        "url": str,
    },
)
AgeRestrictionJson = TypedDict(
    "AgeRestrictionJson",
    {
        "id": int,
        "label": str,
    },
)
AnimeTypeJson = TypedDict(
    "AnimeTypeJson",
    {
        "id": int,
        "label": str,
    },
)
AnimeStatusJson = TypedDict(
    "AnimeStatusJson",
    {
        "id": int,
        "label": str,
    },
)
ModeratedJson = TypedDict(
    "ModeratedJson",
    {
        "id": int,
        "label": str,
    },
)
RatingJson = TypedDict(
    "RatingJson",
    {
        "average": str,
        "averageFormated": str,
        "votes": int,
        "votesFormated": str,
        "user": int,
    },
)
ViewsJson = TypedDict(
    "ViewsJson",
    {
        "total": int,
        "short": str,
        "formated": str,
    },
)
GenreJson = TypedDict(
    "GenreJson",
    {
        "id": int,
        "name": str,
        "adult": bool,
        "alert": bool,
    },
)
TagJson = TypedDict(
    "TagJson",
    {
        "id": int,
        "name": str,
        "adult": bool,
        "alert": bool,
    },
)
SubscriptionJson = TypedDict(
    "SubscriptionJson",
    {
        "is_subscribed": bool,
        "source_type": str,
        "source_id": int,
        "relation": Optional[str],
    },
)
AvatarJson = TypedDict(
    "AvatarJson",
    {
        "filename": str,
        "url": str,
    },
)
PremiumJson = TypedDict(
    "PremiumJson",
    {
        "enabled": bool,
    },
)
TimeJson = TypedDict(
    "TimeJson",
    {
        "value": int,
        "formatted": str,
    },
)
ItemsCountJson = TypedDict(
    "ItemsCountJson",
    {
        "uploaded": int,
        "total": int,
    },
)
TranslationTypeJson = TypedDict(
    "TranslationTypeJson",
    {
        "id": int,
        "label": str,
    },
)
EpisodeStatusJson = TypedDict(
    "EpisodeStatusJson",
    {
        "id": str,
        "label": str,
        "abbr": Optional[str],
    },
)
StatJson = TypedDict(
    "StatJson",
    {
        "value": float,
        "formated": str,
        "short": str,
        "label": str,
        "tag": str,
    },
)
QualityJson = TypedDict(
    "QualityJson",
    {
        "href": str,
        "quality": int,
        "bitrate": int,
    },
)
PaginationJson = TypedDict(
    "PaginationJson",
    {
        "first": str,
        "last": Optional[str],
        "prev": Optional[str],
        "next": str,
    },
)
PaginationMetaJson = TypedDict(
    "PaginationMetaJson",
    {
        "current_page": int,
        "from": int,
        "path": str,
        "per_page": int,
        "to": int,
        "seed": str,
    },
)
ErrorToastJson = TypedDict(
    "ErrorToastJson",
    {
        "type": str,
        "message": str,
    },
)
ApiErrorJson = TypedDict(
    "ApiErrorJson",
    {
        "error": Optional[str],
        "toast": NotRequired[ErrorToastJson],
    },
)
TeamJson = TypedDict(
    "TeamJson",
    {
        "id": int,
        "slug": str,
        "slug_url": str,
        "model": str,
        "name": str,
        "cover": CoverJson,
        "donate_enabled": Optional[str],
    },
)
TeamWithStatsJson = TypedDict(
    "TeamWithStatsJson",
    {
        "id": int,
        "slug": str,
        "slug_url": str,
        "model": str,
        "name": str,
        "cover": CoverJson,
        "donate_enabled": Optional[str],
        "stats": List[StatJson],
    },
)
PublisherJson = TypedDict(
    "PublisherJson",
    {
        "id": int,
        "slug": str,
        "slug_url": str,
        "model": str,
        "name": str,
        "rus_name": Optional[str],
        "cover": CoverJson,
        "subscription": SubscriptionJson,
    },
)
AuthorJson = TypedDict(
    "AuthorJson",
    {
        "id": int,
        "slug": str,
        "slug_url": str,
        "model": str,
        "name": str,
        "rus_name": Optional[str],
        "alt_name": Optional[str],
        "cover": CoverJson,
        "subscription": SubscriptionJson,
        "confirmed": Optional[str],
        "user_id": int,
    },
)
UserJson = TypedDict(
    "UserJson",
    {
        "id": int,
        "username": str,
        "avatar": AvatarJson,
        "last_online_at": Optional[str],
        "premium": PremiumJson,
    },
)
MetadataCountCharactersJson = TypedDict(
    "MetadataCountCharactersJson",
    {
        "Main": int,
        "Supporting": int,
    },
)
MetadataCountReviewsJson = TypedDict(
    "MetadataCountReviewsJson",
    {
        "neutral": int,
        "positive": int,
        "negative": int,
        "all": int,
    },
)
MetadataCountJson = TypedDict(
    "MetadataCountJson",
    {
        "branches": int,
        "characters": MetadataCountCharactersJson,
        "reviews": MetadataCountReviewsJson,
        "relations": int,
        "people": int,
        "covers": int,
    },
)
MetadataCommentsDisabledJson = TypedDict(
    "MetadataCommentsDisabledJson",
    {
        "media": bool,
        "content": bool,
    },
)
MetadataJson = TypedDict(
    "MetadataJson",
    {
        "close_comments": int,
        "comments_disabled": MetadataCommentsDisabledJson,
        "count": MetadataCountJson,
    },
)
VideoJson = TypedDict(
    "VideoJson",
    {
        "id": int,
        "quality": List[QualityJson],
    },
)
PlayerJson = TypedDict(
    "PlayerJson",
    {
        "id": int,
        "episode_id": int,
        "player": str,
        "translation_type": TranslationTypeJson,
        "team": TeamWithStatsJson,
        "created_at": str,
        "views": int,
        "src": str,
        "video": VideoJson,
    },
)
AnimeListItemJson = TypedDict(
    "AnimeListItemJson",
    {
        "id": int,
        "name": str,
        "rus_name": str,
        "eng_name": str,
        "model": str,
        "slug": str,
        "slug_url": str,
        "cover": CoverJson,
        "ageRestriction": AgeRestrictionJson,
        "site": int,
        "type": AnimeTypeJson,
        "releaseDate": str,
        "rating": RatingJson,
        "content_marking": List[str],
        "status": AnimeStatusJson,
        "releaseDateString": str,
        "shiki_rate": Optional[float],
    },
)
AnimeDetailJson = TypedDict(
    "AnimeDetailJson",
    {
        "id": int,
        "name": str,
        "rus_name": str,
        "eng_name": str,
        "model": str,
        "slug": str,
        "slug_url": str,
        "cover": CoverJson,
        "ageRestriction": AgeRestrictionJson,
        "site": int,
        "type": AnimeTypeJson,
        "releaseDate": str,
        "rating": RatingJson,
        "content_marking": List[str],
        "status": AnimeStatusJson,
        "releaseDateString": str,
        "otherNames": List[str],
        "background": BackgroundJson,
        "summary": str,
        "close_view": int,
        "views": ViewsJson,
        "is_licensed": bool,
        "moderated": ModeratedJson,
        "teams": List[TeamJson],
        "genres": List[GenreJson],
        "tags": List[TagJson],
        "publisher": List[PublisherJson],
        "franchise": List[str],
        "authors": List[AuthorJson],
        "user": UserJson,
        "metadata": MetadataJson,
        "time": TimeJson,
        "items_count": ItemsCountJson,
        "episodes_schedule": List[str],
        "shikimori_href": str,
        "shiki_rate": float,
    },
)
EpisodeListItemJson = TypedDict(
    "EpisodeListItemJson",
    {
        "id": int,
        "model": str,
        "name": str,
        "number": str,
        "number_secondary": str,
        "season": str,
        "status": EpisodeStatusJson,
        "anime_id": int,
        "created_at": str,
        "item_number": int,
        "type": str,
    },
)
EpisodeDetailJson = TypedDict(
    "EpisodeDetailJson",
    {
        "id": int,
        "model": str,
        "name": str,
        "number": str,
        "number_secondary": str,
        "season": str,
        "status": EpisodeStatusJson,
        "anime_id": int,
        "created_at": str,
        "item_number": int,
        "type": str,
        "players": List[PlayerJson],
    },
)
AnimeListResponseJson = TypedDict(
    "AnimeListResponseJson",
    {
        "data": List[AnimeListItemJson],
        "links": PaginationJson,
        "meta": PaginationMetaJson,
    },
)
CountryMetaJson = TypedDict(
    "CountryMetaJson",
    {
        "country": str,
    },
)
AnimeDetailResponseJson = TypedDict(
    "AnimeDetailResponseJson",
    {
        "data": AnimeDetailJson,
        "meta": CountryMetaJson,
    },
)
EpisodeListResponseJson = TypedDict(
    "EpisodeListResponseJson",
    {
        "data": List[EpisodeListItemJson],
    },
)
EpisodeDetailResponseJson = TypedDict(
    "EpisodeDetailResponseJson",
    {
        "data": EpisodeDetailJson,
    },
)


@dataclass(frozen=True)
class AnimelibOrgApiErr404(Err[ApiErrorJson]):
    status: Literal[404] = 404


@dataclass(frozen=True)
class AnimelibOrgApiErr400(Err[ApiErrorJson]):
    status: Literal[400] = 400


ListAnimeResult = Union[Ok[AnimeListResponseJson], AnimelibOrgApiErr404, AnimelibOrgApiErr400, UnknownErr, TransportErr]
GetAnimeResult = Union[
    Ok[AnimeDetailResponseJson], AnimelibOrgApiErr404, AnimelibOrgApiErr400, UnknownErr, TransportErr
]
ListEpisodesResult = Union[
    Ok[EpisodeListResponseJson], AnimelibOrgApiErr404, AnimelibOrgApiErr400, UnknownErr, TransportErr
]
GetEpisodeResult = Union[
    Ok[EpisodeDetailResponseJson], AnimelibOrgApiErr404, AnimelibOrgApiErr400, UnknownErr, TransportErr
]


class AnimelibOrgApi:
    @staticmethod
    def ssc_dispatch_err(
        _status: int, _headers: Mapping[str, str], _body: Any
    ) -> Union[AnimelibOrgApiErr404, AnimelibOrgApiErr400, UnknownErr, None]:
        if 200 <= _status < 300:
            return None
        if _status == 404:
            return AnimelibOrgApiErr404(headers=_headers, value=_body)
        if _status == 400:
            return AnimelibOrgApiErr400(headers=_headers, value=_body)
        return UnknownErr(status=_status, headers=_headers, value=_body)

    """
    Animelib.org API client (cdnlibs.org backend).
    
    Generated methods (Python, --http-client httpx):
        list_anime(client, *, fields=None, site_id=None, q=None, status=None, sort_by=None, page=None)
        get_anime(client, *, slug_url, fields=None)
        list_episodes(client, *, anime_id=None)
        get_episode(client, *, id)
    """

    @classmethod
    def list_anime(
        cls,
        client: httpx.Client,
        *,
        fields: Optional[List[str]] = None,
        site_id: Optional[List[int]] = None,
        q: Optional[str] = None,
        status: Optional[List[int]] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
    ) -> ListAnimeResult:
        """Search or list anime with optional filters, ongoings, and pagination."""
        _params: dict = {}
        if fields is not None:
            _params["fields[]"] = fields
        if site_id is not None:
            _params["site_id[]"] = site_id
        if q is not None:
            _params["q"] = q
        if status is not None:
            _params["status[]"] = status
        if sort_by is not None:
            _params["sort_by"] = sort_by
        if page is not None:
            _params["page"] = page
        try:
            _resp = client.request(
                "GET",
                "https://api.cdnlibs.org/anime",
                headers={"Accept": "application/json"},
                params=_params,
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_list_anime(
        cls,
        client: httpx.AsyncClient,
        *,
        fields: Optional[List[str]] = None,
        site_id: Optional[List[int]] = None,
        q: Optional[str] = None,
        status: Optional[List[int]] = None,
        sort_by: Optional[str] = None,
        page: Optional[int] = None,
    ) -> ListAnimeResult:
        """Search or list anime with optional filters, ongoings, and pagination."""
        _params: dict = {}
        if fields is not None:
            _params["fields[]"] = fields
        if site_id is not None:
            _params["site_id[]"] = site_id
        if q is not None:
            _params["q"] = q
        if status is not None:
            _params["status[]"] = status
        if sort_by is not None:
            _params["sort_by"] = sort_by
        if page is not None:
            _params["page"] = page
        try:
            _resp = await client.request(
                "GET",
                "https://api.cdnlibs.org/anime",
                headers={"Accept": "application/json"},
                params=_params,
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    def get_anime(cls, client: httpx.Client, *, slug_url: str, fields: Optional[List[str]] = None) -> GetAnimeResult:
        """Get anime details by slug_url (e.g. '316--serial-experiments-lain-anime')."""
        _params: dict = {}
        if fields is not None:
            _params["fields[]"] = fields
        try:
            _resp = client.request(
                "GET",
                f"https://api.cdnlibs.org/anime/{slug_url}",
                headers={"Accept": "application/json"},
                params=_params,
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_get_anime(
        cls, client: httpx.AsyncClient, *, slug_url: str, fields: Optional[List[str]] = None
    ) -> GetAnimeResult:
        """Get anime details by slug_url (e.g. '316--serial-experiments-lain-anime')."""
        _params: dict = {}
        if fields is not None:
            _params["fields[]"] = fields
        try:
            _resp = await client.request(
                "GET",
                f"https://api.cdnlibs.org/anime/{slug_url}",
                headers={"Accept": "application/json"},
                params=_params,
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    def list_episodes(cls, client: httpx.Client, *, anime_id: Optional[str] = None) -> ListEpisodesResult:
        """List episodes for an anime by slug_url."""
        _params: dict = {}
        if anime_id is not None:
            _params["anime_id"] = anime_id
        try:
            _resp = client.request(
                "GET",
                "https://api.cdnlibs.org/episodes",
                headers={"Accept": "application/json"},
                params=_params,
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_list_episodes(
        cls, client: httpx.AsyncClient, *, anime_id: Optional[str] = None
    ) -> ListEpisodesResult:
        """List episodes for an anime by slug_url."""
        _params: dict = {}
        if anime_id is not None:
            _params["anime_id"] = anime_id
        try:
            _resp = await client.request(
                "GET",
                "https://api.cdnlibs.org/episodes",
                headers={"Accept": "application/json"},
                params=_params,
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    def get_episode(cls, client: httpx.Client, *, id: int) -> GetEpisodeResult:
        """Get episode details with player and dubbing info by episode ID."""
        try:
            _resp = client.request(
                "GET",
                f"https://api.cdnlibs.org/episodes/{id}",
                headers={"Accept": "application/json"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_get_episode(cls, client: httpx.AsyncClient, *, id: int) -> GetEpisodeResult:
        """Get episode details with player and dubbing info by episode ID."""
        try:
            _resp = await client.request(
                "GET",
                f"https://api.cdnlibs.org/episodes/{id}",
                headers={"Accept": "application/json"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)
