# autogenerated by ssc-gen. DO NOT EDIT
""""""

from dataclasses import dataclass
from typing import TypedDict, Optional, Any, List, Union, Literal, Mapping

import httpx
from .sscgen_runtime import (
    Ok,
    Err,
    UnknownErr,
    TransportErr,
    ssc_parse_response,
)

ItemJson = TypedDict(
    "ItemJson",
    {
        "id": int,
        "title": str,
        "description": str,
        "genre": str,
        "year": str,
        "urlImagePreview": str,
        "screenImage": List[str],
        "isFavorite": int,
        "isLikes": int,
        "rating": float,
        "votes": int,
        "timer": float,
        "type": str,
        "director": str,
        "series": str,
    },
)
StateJson = TypedDict(
    "StateJson",
    {
        "status": str,
        "rek": int,
        "page": int,
        "count": int,
    },
)
SearchResponseJson = TypedDict(
    "SearchResponseJson",
    {
        "state": StateJson,
        "data": List[ItemJson],
    },
)
PlaylistResponseJson = TypedDict(
    "PlaylistResponseJson",
    {
        "name": str,
        "hd": str,
        "std": str,
        "preview": str,
    },
)
ResponseErrorJson = TypedDict(
    "ResponseErrorJson",
    {
        "status": Optional[str],
        "error": str,
    },
)


@dataclass(frozen=True)
class AnimeVostAPIErr404(Err[ResponseErrorJson]):
    status: Literal[404] = 404


@dataclass(frozen=True)
class AnimeVostAPIErr200Error(Err[ResponseErrorJson]):
    status: Literal[200] = 200


SearchResult = Union[Ok[SearchResponseJson], AnimeVostAPIErr404, AnimeVostAPIErr200Error, UnknownErr, TransportErr]
LastResult = Union[Ok[SearchResponseJson], AnimeVostAPIErr404, AnimeVostAPIErr200Error, UnknownErr, TransportErr]
PlaylistResult = Union[
    Ok[List[PlaylistResponseJson]], AnimeVostAPIErr404, AnimeVostAPIErr200Error, UnknownErr, TransportErr
]


class AnimeVostAPI:
    @staticmethod
    def ssc_dispatch_err(
        _status: int, _headers: Mapping[str, str], _body: Any
    ) -> Union[AnimeVostAPIErr404, AnimeVostAPIErr200Error, UnknownErr, None]:
        if 200 <= _status < 300:
            if isinstance(_body, dict):
                if _status == 200 and "error" in _body:
                    return AnimeVostAPIErr200Error(headers=_headers, value=_body)
            return None
        if _status == 404:
            return AnimeVostAPIErr404(headers=_headers, value=_body)
        return UnknownErr(status=_status, headers=_headers, value=_body)

    @classmethod
    def search(cls, client: httpx.Client, *, query: str) -> SearchResult:
        try:
            _resp = client.request(
                "POST",
                "https://api.animevost.org/v1/search",
                headers={"Content-Type": "application/x-www-form-urlencoded"},
                data={"name": query},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_search(cls, client: httpx.AsyncClient, *, query: str) -> SearchResult:
        try:
            _resp = await client.request(
                "POST",
                "https://api.animevost.org/v1/search",
                headers={"Content-Type": "application/x-www-form-urlencoded"},
                data={"name": query},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    def last(cls, client: httpx.Client, *, page: int, quantity: int) -> LastResult:
        try:
            _resp = client.request(
                "GET",
                "https://api.animevost.org/v1/last",
                params={"page": page, "quantity": quantity},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_last(cls, client: httpx.AsyncClient, *, page: int, quantity: int) -> LastResult:
        try:
            _resp = await client.request(
                "GET",
                "https://api.animevost.org/v1/last",
                params={"page": page, "quantity": quantity},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    def playlist(cls, client: httpx.Client, *, id: int) -> PlaylistResult:
        try:
            _resp = client.request(
                "POST",
                "https://api.animevost.org/v1/playlist",
                headers={"Content-Type": "application/x-www-form-urlencoded"},
                data={"id": id},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_playlist(cls, client: httpx.AsyncClient, *, id: int) -> PlaylistResult:
        try:
            _resp = await client.request(
                "POST",
                "https://api.animevost.org/v1/playlist",
                headers={"Content-Type": "application/x-www-form-urlencoded"},
                data={"id": id},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)
