# autogenerated by ssc-gen. DO NOT EDIT
'\nThanks https://github.com/barsikus007 for researches and decoder impl\n\nNOTE: for extract Search and Ongoing items use rest-api requests\n\nOngoing:\n        POST https://dreamerscast.com/"\n        {\'search\': "", "status": "", "pageSize": 16, \'pageNumber\': 1}\n\nSearch:\n\n    POST https://dreamerscast.com/"\n    {\'search\': "<QUERY>", "status": "", "pageSize": 16, \'pageNumber\': 1}\n\n\nFor extract playlist required reverse obfuscated playlist data and obfuscated javascript player'

from lxml import html
from lxml.html import HtmlElement
from typing import Any, Dict, List, Optional, TypedDict, Union
from typing import cast
import httpx

from .sscgen_runtime import (
    FALLBACK_HTML_STR,
    Ok,
    UnknownErr,
    TransportErr,
    ErrMatcher,
    ssc_rest_call,
    ssc_rest_call_async,
)

from .sscgen_runtime import std_re_search

ReleaseJson = TypedDict(
    "ReleaseJson",
    {
        "id": int,
        "russian": Optional[str],
        "original": str,
        "image": str,
        "wall": Optional[str],
        "description": Optional[str],
        "status": Optional[str],
        "type": str,
        "dateissue": int,
        "season": str,
        "genres": str,
        "studio": str,
        "duration": int,
        "series": int,
        "currentSeries": int,
        "dubbers": str,
        "timers": str,
        "user": Optional[str],
        "url": str,
        "views": int,
        "rating": str,
        "date": Optional[str],
        "update": Optional[str],
    },
)
DreamCastResponseJson = TypedDict(
    "DreamCastResponseJson",
    {
        "releases": List[ReleaseJson],
        "count": int,
    },
)
PageAnimeType = TypedDict(
    "PageAnimeType",
    {
        "title": str,
        "description": str,
        "thumbnail": str,
        "player_js_encoded": str,
        "player_js_url": str,
    },
)
SearchResult = Union[Ok[DreamCastResponseJson], UnknownErr, TransportErr]

OngoingResult = Union[Ok[DreamCastResponseJson], UnknownErr, TransportErr]

DREAMCAST_API_MATCHERS: List[ErrMatcher] = []


class DreamcastAPI:
    @classmethod
    def search(cls, client: httpx.Client, *, query: str, **kwargs: Any) -> SearchResult:
        _kw: Dict[str, Any] = {}
        _kw["headers"] = {
            "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
            "X-Requested-With": "XMLHttpRequest",
            "Origin": "https://dreamerscast.com",
            "Referer": "https://dreamerscast.com/",
        }
        _kw["data"] = {"search": query, "status": "", "pageSize": "16", "pageNumber": "1"}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        return cast(
            SearchResult,
            ssc_rest_call(
                client,
                DREAMCAST_API_MATCHERS,
                "POST",
                "https://dreamerscast.com/",
                **_kw,
            ),
        )

    @classmethod
    async def async_search(cls, client: httpx.AsyncClient, *, query: str, **kwargs: Any) -> SearchResult:
        _kw: Dict[str, Any] = {}
        _kw["headers"] = {
            "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
            "X-Requested-With": "XMLHttpRequest",
            "Origin": "https://dreamerscast.com",
            "Referer": "https://dreamerscast.com/",
        }
        _kw["data"] = {"search": query, "status": "", "pageSize": "16", "pageNumber": "1"}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        return cast(
            SearchResult,
            await ssc_rest_call_async(
                client,
                DREAMCAST_API_MATCHERS,
                "POST",
                "https://dreamerscast.com/",
                **_kw,
            ),
        )

    @classmethod
    def ongoing(cls, client: httpx.Client, **kwargs: Any) -> OngoingResult:
        _kw: Dict[str, Any] = {}
        _kw["headers"] = {
            "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
            "X-Requested-With": "XMLHttpRequest",
            "Origin": "https://dreamerscast.com",
            "Referer": "https://dreamerscast.com/",
        }
        _kw["data"] = {"search": "", "status": "", "pageSize": "16", "pageNumber": "1"}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        return cast(
            OngoingResult,
            ssc_rest_call(
                client,
                DREAMCAST_API_MATCHERS,
                "POST",
                "https://dreamerscast.com/",
                **_kw,
            ),
        )

    @classmethod
    async def async_ongoing(cls, client: httpx.AsyncClient, **kwargs: Any) -> OngoingResult:
        _kw: Dict[str, Any] = {}
        _kw["headers"] = {
            "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
            "X-Requested-With": "XMLHttpRequest",
            "Origin": "https://dreamerscast.com",
            "Referer": "https://dreamerscast.com/",
        }
        _kw["data"] = {"search": "", "status": "", "pageSize": "16", "pageNumber": "1"}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        return cast(
            OngoingResult,
            await ssc_rest_call_async(
                client,
                DREAMCAST_API_MATCHERS,
                "POST",
                "https://dreamerscast.com/",
                **_kw,
            ),
        )


class PageAnime:
    "Usage example:\n\nGET https://dreamerscast.com/home/release/323-tensei-kizoku-kantei-skill-de-nariagaru-2\n\nEncoding (24.12.24 actual step-by-step)\n\ndecoding and extract playlist:\n\n- GET <player_js_url>\n- unpack, extract encoded symbols\n- by <player_js_encoded> and <player_js_url> values decrypt it (implement logic from original player sources)"

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        else:
            self._doc = document

    @classmethod
    def fetch(cls, client: httpx.Client, *, url_path: str, **kwargs: Any) -> "PageAnime":
        _kw: Dict[str, Any] = {}
        _kw["headers"] = {"Referer": "https://dreamerscast.com/"}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        _resp = client.request(
            "GET",
            f"https://dreamerscast.com{url_path}",
            **_kw,
        )
        _resp.raise_for_status()
        _body = _resp.text
        return cls(_body)

    @classmethod
    async def async_fetch(cls, client: httpx.AsyncClient, *, url_path: str, **kwargs: Any) -> "PageAnime":
        _kw: Dict[str, Any] = {}
        _kw["headers"] = {"Referer": "https://dreamerscast.com/"}
        for _k, _v in kwargs.items():
            if isinstance(_kw.get(_k), dict) and isinstance(_v, dict):
                _kw[_k] = {**_kw[_k], **_v}
            else:
                _kw[_k] = _v
        _resp = await client.request(
            "GET",
            f"https://dreamerscast.com{url_path}",
            **_kw,
        )
        _resp.raise_for_status()
        _body = _resp.text
        return cls(_body)

    def _parse_title(self, v: HtmlElement) -> str:
        v1 = v.cssselect("h3")[0]
        v2 = v1.text_content()
        return v2

    def _parse_description(self, v: HtmlElement) -> str:
        try:
            v1 = v.cssselect(".postDesc")[0]
            v2 = v1.text_content()
            return v2
        except Exception:
            return None

    def _parse_thumbnail(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".details_poster img")[0]
        v2 = v1.get("src", "")
        v3 = "https:{}".format(v2)
        return v3

    def _parse_player_js_encoded(self, v: HtmlElement) -> str:
        v1 = html.tostring(v, encoding="unicode")
        v2 = std_re_search(
            'new Playerjs\\("(.*?)"\\)',
            v1,
            'dreamerscast_parser.kdl:141:30 re-match failed at PageAnime.player_js_encoded pattern=new Playerjs\\("(.*?)"\\)',
        )
        return v2

    def _parse_player_js_url(self, v: HtmlElement) -> str:
        v1 = html.tostring(v, encoding="unicode")
        v2 = std_re_search(
            '<script[^>]+src="(/js/playerjs.*?)"',
            v1,
            'dreamerscast_parser.kdl:142:26 re-match failed at PageAnime.player_js_url pattern=<script[^>]+src="(/js/playerjs.*?)"',
        )
        v3 = "https://dreamerscast.com{}".format(v2)
        return v3

    def parse(self) -> PageAnimeType:
        return {
            "title": self._parse_title(self._doc),
            "description": self._parse_description(self._doc),
            "thumbnail": self._parse_thumbnail(self._doc),
            "player_js_encoded": self._parse_player_js_encoded(self._doc),
            "player_js_url": self._parse_player_js_url(self._doc),
        }
