# autogenerated by ssc-gen. DO NOT EDIT
"""
Thanks https://github.com/barsikus007 for researches and decoder impl

NOTE: for extract Search and Ongoing items use rest-api requests

Ongoing:
        POST https://dreamerscast.com/"
        {'search': "", "status": "", "pageSize": 16, 'pageNumber': 1}

Search:

    POST https://dreamerscast.com/"
    {'search': "<QUERY>", "status": "", "pageSize": 16, 'pageNumber': 1}


For extract playlist required reverse obfuscated playlist data and obfuscated javascript player"""

import re
from typing import TypedDict, Optional, Any, List, Union, Mapping

from lxml import html
from lxml.html import HtmlElement
import httpx
from .sscgen_runtime import (
    Ok,
    UnknownErr,
    TransportErr,
    ssc_parse_response,
    FALLBACK_HTML_STR,
)

ReleaseJson = TypedDict(
    "ReleaseJson",
    {
        "id": int,
        "russian": Optional[str],
        "original": str,
        "image": str,
        "wall": Optional[str],
        "description": Optional[str],
        "status": Optional[str],
        "type": str,
        "dateissue": int,
        "season": str,
        "genres": str,
        "studio": str,
        "duration": int,
        "series": int,
        "currentSeries": int,
        "dubbers": str,
        "timers": str,
        "user": Optional[str],
        "url": str,
        "views": int,
        "rating": str,
        "date": Optional[str],
        "update": Optional[str],
    },
)
DreamCastResponseJson = TypedDict(
    "DreamCastResponseJson",
    {
        "releases": List[ReleaseJson],
        "count": int,
    },
)


class PageAnimeType(TypedDict):
    title: str
    description: Optional[str]
    thumbnail: str
    player_js_encoded: str
    player_js_url: str


SearchResult = Union[Ok[DreamCastResponseJson], UnknownErr, TransportErr]
OngoingResult = Union[Ok[DreamCastResponseJson], UnknownErr, TransportErr]


class DreamcastAPI:
    @staticmethod
    def ssc_dispatch_err(_status: int, _headers: Mapping[str, str], _body: Any) -> Union[UnknownErr, None]:
        if 200 <= _status < 300:
            return None
        return UnknownErr(status=_status, headers=_headers, value=_body)

    @classmethod
    def search(cls, client: httpx.Client, *, query: str) -> SearchResult:
        try:
            _resp = client.request(
                "POST",
                "https://dreamerscast.com/",
                headers={
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "X-Requested-With": "XMLHttpRequest",
                    "Origin": "https://dreamerscast.com",
                    "Referer": "https://dreamerscast.com/",
                },
                data={"search": query, "status": "", "pageSize": "16", "pageNumber": "1"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_search(cls, client: httpx.AsyncClient, *, query: str) -> SearchResult:
        try:
            _resp = await client.request(
                "POST",
                "https://dreamerscast.com/",
                headers={
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "X-Requested-With": "XMLHttpRequest",
                    "Origin": "https://dreamerscast.com",
                    "Referer": "https://dreamerscast.com/",
                },
                data={"search": query, "status": "", "pageSize": "16", "pageNumber": "1"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    def ongoing(cls, client: httpx.Client) -> OngoingResult:
        try:
            _resp = client.request(
                "POST",
                "https://dreamerscast.com/",
                headers={
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "X-Requested-With": "XMLHttpRequest",
                    "Origin": "https://dreamerscast.com",
                    "Referer": "https://dreamerscast.com/",
                },
                data={"search": "", "status": "", "pageSize": "16", "pageNumber": "1"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)

    @classmethod
    async def async_ongoing(cls, client: httpx.AsyncClient) -> OngoingResult:
        try:
            _resp = await client.request(
                "POST",
                "https://dreamerscast.com/",
                headers={
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "X-Requested-With": "XMLHttpRequest",
                    "Origin": "https://dreamerscast.com",
                    "Referer": "https://dreamerscast.com/",
                },
                data={"search": "", "status": "", "pageSize": "16", "pageNumber": "1"},
            )
        except httpx.HTTPError as _exc:
            return TransportErr(cause=repr(_exc))
        _status, _headers, _body = ssc_parse_response(_resp)
        _err = cls.ssc_dispatch_err(_status, _headers, _body)
        if _err is not None:
            return _err
        return Ok(status=_status, headers=_headers, value=_body)


class PageAnime:
    """
    Usage example:

    GET https://dreamerscast.com/home/release/323-tensei-kizoku-kantei-skill-de-nariagaru-2

    Encoding (24.12.24 actual step-by-step)

    decoding and extract playlist:

    - GET <player_js_url>
    - unpack, extract encoded symbols
    - by <player_js_encoded> and <player_js_url> values decrypt it (implement logic from original player sources)
    """

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, HtmlElement):
            self._doc = document
        elif isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)

    @classmethod
    def fetch(cls, client: httpx.Client, *, url_path: str) -> "PageAnime":
        _resp = client.request(
            "GET",
            f"https://dreamerscast.com{url_path}",
            headers={"Referer": "https://dreamerscast.com/"},
        )
        _resp.raise_for_status()
        _body = _resp.text
        return cls(_body)

    @classmethod
    async def async_fetch(cls, client: httpx.AsyncClient, *, url_path: str) -> "PageAnime":
        _resp = await client.request(
            "GET",
            f"https://dreamerscast.com{url_path}",
            headers={"Referer": "https://dreamerscast.com/"},
        )
        _resp.raise_for_status()
        _body = _resp.text
        return cls(_body)

    def _parse_title(self, v: HtmlElement) -> str:
        v1 = v.cssselect("h3")[0]
        v2 = v1.text_content()
        return v2

    def _parse_description(self, v: HtmlElement) -> Optional[str]:
        try:
            v1 = v.cssselect(".postDesc")[0]
            v2 = v1.text_content()
        except Exception:
            return None
        return v2

    def _parse_thumbnail(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".details_poster img")[0]
        v2 = v1.get("src", "")
        v3 = "https:{}".format(v2)
        return v3

    def _parse_player_js_encoded(self, v: HtmlElement) -> str:
        v1 = html.tostring(v, encoding="unicode")
        v2 = re.search('new Playerjs\\("(.*?)"\\)', v1)[1]
        return v2

    def _parse_player_js_url(self, v: HtmlElement) -> str:
        v1 = html.tostring(v, encoding="unicode")
        v2 = re.search('<script[^>]+src="(/js/playerjs.*?)"', v1)[1]
        v3 = "https://dreamerscast.com{}".format(v2)
        return v3

    def parse(self) -> PageAnimeType:
        return {
            "title": self._parse_title(self._doc),
            "description": self._parse_description(self._doc),
            "thumbnail": self._parse_thumbnail(self._doc),
            "player_js_encoded": self._parse_player_js_encoded(self._doc),
            "player_js_url": self._parse_player_js_url(self._doc),
        }
