# autogenerated by ssc-gen. DO NOT EDIT
""""""

import re
import sys
from typing import TypedDict, Optional, List, Dict, Union
from html import unescape as _html_unescape
from lxml import html
from lxml.html import HtmlElement

FALLBACK_HTML_STR = "<html><body></body></html>"
_RE_HEX_ENTITY = re.compile(r"&#x([0-9a-fA-F]+);")
_RE_UNICODE_ENTITY = re.compile(r"\\u([0-9a-fA-F]{4})")
_RE_BYTES_ENTITY = re.compile(r"\\x([0-9a-fA-F]{2})")
_RE_CHARS_MAP = {"\\b": "\\b", "\\f": "\\f", "\\n": "\\n", "\\r": "\\r", "\\t": "\\t"}


def repl_map(s: str, rmap: Dict[str, str]) -> str:
    for k, v in rmap.items():
        s = s.replace(k, v)
    return s


def normalize_text(text: str) -> str:
    return " ".join(text.split()) if text else ""


class _UnmatchedTableRow:
    pass


def unescape_text(text: str) -> str:
    s = _html_unescape(text)
    s = _RE_HEX_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
    s = _RE_UNICODE_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
    s = _RE_BYTES_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
    for ch, r in _RE_CHARS_MAP.items():
        s = s.replace(ch, r)
    return s


if sys.version_info >= (3, 9):

    def rm_prefix(s: str, p: str) -> str:
        return s.removeprefix(p)

    def rm_suffix(s: str, p: str) -> str:
        return s.removesuffix(p)


else:

    def rm_prefix(s: str, p: str) -> str:
        return s[len(p) :] if s.startswith(p) else s

    def rm_suffix(s: str, p: str) -> str:
        return s[: -(len(p))] if s.endswith(p) else s


UNMATCHED_TABLE_ROW = _UnmatchedTableRow()


class PageUtilsType(TypedDict):
    url: str


class PageOngoingType(TypedDict):
    thumbnail_path: str
    url: str
    episode: int
    title: str


class PageSearchType(TypedDict):
    title: str
    thumbnail_path: str
    url: str


class PageAnimeType(TypedDict):
    title: str
    alt_title: Optional[str]
    description: str
    thumbnail: str


class PageUtils:
    """
    helper stuct for extract canonical URL
    """

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, HtmlElement):
            self._doc = document
        elif isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)

    def _parse_url(self, v: HtmlElement) -> str:
        v1 = v.cssselect('link[rel="canonical"], link[rel="alternate"]')[0]
        v2 = v1.get("href", "")
        v3 = v2.rstrip("/")
        v4 = rm_suffix(v3, "/rss.xml")
        return v4

    def parse(self) -> PageUtilsType:
        return {
            "url": self._parse_url(self._doc),
        }


class PageOngoing:
    """

    Get all available ongoings from the main page

    can be change domains, use PageUtils struct or
    extract from `link[rel="canonical"]` element

    USAGE:
        GET https://yummyanime.in/

    """

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, HtmlElement):
            self._doc = document
        elif isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)

    def _split_doc(self, v: HtmlElement) -> List[HtmlElement]:
        v1 = v.cssselect("a.grid-item")
        return v1

    def _parse_thumbnail_path(self, v: HtmlElement) -> str:
        v1 = v.cssselect("img[data-src]")[0]
        v2 = v1.get("data-src", "")
        return v2

    def _parse_url(self, v: HtmlElement) -> str:
        v1 = v.get("href", "")
        return v1

    def _parse_episode(self, v: HtmlElement) -> int:
        try:
            v1 = v.cssselect(".poster__label")[0]
            v2 = v1.text_content()
            v3 = re.search("(\\d+)\\s", v2)[1]
            v4 = int(v3)
        except Exception:
            return 1
        return v4

    def _parse_title(self, v: HtmlElement) -> str:
        v1 = v.cssselect("h3")[0]
        v2 = v1.text_content()
        v3 = v2.strip()
        return v3

    def parse(self) -> List[PageOngoingType]:
        return [
            {
                "thumbnail_path": self._parse_thumbnail_path(i),
                "url": self._parse_url(i),
                "episode": self._parse_episode(i),
                "title": self._parse_title(i),
            }
            for i in self._split_doc(self._doc)
        ]


class PageSearch:
    """

    Get search results

    USAGE:

        POST https://yummyanime.in
        do=search&subaction=search&story=<QUERY>

    EXAMPLE:

        POST https://yummyanime.in/index.php
        do=search&subaction=search=from_page=0story=ван-пис

    """

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, HtmlElement):
            self._doc = document
        elif isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)

    def _split_doc(self, v: HtmlElement) -> List[HtmlElement]:
        v1 = v.cssselect("a.has-overlay")
        return v1

    def _parse_title(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".poster__title")[0]
        v2 = v1.text_content()
        return v2

    def _parse_thumbnail_path(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".xfieldimage[data-src]")[0]
        v2 = v1.get("data-src", "")
        return v2

    def _parse_url(self, v: HtmlElement) -> str:
        v1 = v.get("href", "")
        return v1

    def parse(self) -> List[PageSearchType]:
        return [
            {
                "title": self._parse_title(i),
                "thumbnail_path": self._parse_thumbnail_path(i),
                "url": self._parse_url(i),
            }
            for i in self._split_doc(self._doc)
        ]


class PageAnime:
    """

    get anime page

    USAGE:

        GET https://yummyanime.in/<...>.html

    EXAMPLE:

        GET https://yummyanime.in/4790-vedma-i-chudovische.html

    """

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, HtmlElement):
            self._doc = document
        elif isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)

    def _parse_title(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".anime__title h1")[0]
        v2 = v1.text_content()
        return v2

    def _parse_alt_title(self, v: HtmlElement) -> Optional[str]:
        try:
            v1 = v.cssselect(".anime__title .pmovie__original-title")[0]
            v2 = v1.text_content()
        except Exception:
            return None
        return v2

    def _parse_description(self, v: HtmlElement) -> str:
        try:
            v1 = v.cssselect(".page__text")
            v2 = [i.text_content() for i in v1]
            v3 = "".join(v2)
        except Exception:
            return ""
        return v3

    def _parse_thumbnail(self, v: HtmlElement) -> str:
        v1 = v.cssselect(".pmovie__poster .xfieldimage[data-src]")[0]
        v2 = v1.get("data-src", "")
        return v2

    def parse(self) -> PageAnimeType:
        return {
            "title": self._parse_title(self._doc),
            "alt_title": self._parse_alt_title(self._doc),
            "description": self._parse_description(self._doc),
            "thumbnail": self._parse_thumbnail(self._doc),
        }
