# autogenerated by ssc-gen. DO NOT EDIT
"""
REST API client for YummyAnime (https://yummy-anime.ru).

API base: https://api.yani.tv
Swagger UI: https://yummy-anime.ru/api/swagger

All responses use {"response": <data>} envelope.
Errors (on HTTP 200) use {"error": "...", "error_title": "...", "error_code": N, "error_name": "..."}.
No authentication required.
"""

from typing import List, Optional, TypedDict, Union
from typing_extensions import NotRequired
from dataclasses import dataclass
from typing import Literal
from typing import cast
import httpx
from .sscgen_runtime import (
    Ok,
    Err,
    UnknownErr,
    TransportErr,
    ErrMatcher,
    ssc_rest_call,
    ssc_rest_call_async,
)

PosterJson = TypedDict(
    "PosterJson",
    {
        "fullsize": str,
        "big": str,
        "small": str,
        "medium": str,
        "huge": str,
        "mega": str,
    },
)
RatingJson = TypedDict(
    "RatingJson",
    {
        "average": float,
        "counters": int,
        "kp_rating": float,
        "anidub_rating": int,
        "myanimelist_rating": float,
        "worldart_rating": float,
        "shikimori_rating": float,
    },
)
MinAgeJson = TypedDict(
    "MinAgeJson",
    {
        "value": int,
        "title_long": str,
        "title": str,
    },
)
AnimeStatusJson = TypedDict(
    "AnimeStatusJson",
    {
        "value": int,
        "title": str,
        "alias": str,
        "class": str,
    },
)
AnimeTypeJson = TypedDict(
    "AnimeTypeJson",
    {
        "name": str,
        "value": int,
        "shortname": str,
        "alias": str,
    },
)
RemoteIdsJson = TypedDict(
    "RemoteIdsJson",
    {
        "worldart_id": int,
        "shikimori_id": int,
        "anidub_id": int,
        "anilibria_alias": str,
        "myanimelist_id": int,
        "kp_id": int,
        "worldart_type": str,
        "sr_id": int,
    },
)
TopJson = TypedDict(
    "TopJson",
    {
        "category": int,
        "global": int,
    },
)
GenreShortJson = TypedDict(
    "GenreShortJson",
    {
        "title": str,
        "url": str,
        "id": int,
        "alias": str,
    },
)
EpisodesJson = TypedDict(
    "EpisodesJson",
    {
        "count": int,
        "aired": int,
        "next_date": int,
        "prev_date": int,
    },
)
VideoDataJson = TypedDict(
    "VideoDataJson",
    {
        "player": str,
        "dubbing": str,
        "player_id": int,
    },
)
SkipInfoJson = TypedDict(
    "SkipInfoJson",
    {
        "time": int,
        "length": int,
    },
)
SkipsJson = TypedDict(
    "SkipsJson",
    {
        "opening": NotRequired[SkipInfoJson],
        "ending": NotRequired[SkipInfoJson],
    },
)
GenreJson = TypedDict(
    "GenreJson",
    {
        "title": str,
        "href": str,
        "value": int,
        "more_titles": List[str],
        "group_id": int,
    },
)
GenreGroupJson = TypedDict(
    "GenreGroupJson",
    {
        "title": str,
        "id": int,
    },
)
TypeCountJson = TypedDict(
    "TypeCountJson",
    {
        "count": int,
        "type": AnimeTypeJson,
    },
)
ScheduleItemJson = TypedDict(
    "ScheduleItemJson",
    {
        "description": str,
        "poster": PosterJson,
        "title": str,
        "anime_url": str,
        "anime_id": int,
        "episodes": EpisodesJson,
    },
)
AnimeItemJson = TypedDict(
    "AnimeItemJson",
    {
        "description": str,
        "poster": PosterJson,
        "title": str,
        "anime_url": str,
        "anime_id": int,
        "rating": RatingJson,
        "genres": List[GenreShortJson],
        "year": int,
        "min_age": MinAgeJson,
        "views": int,
        "season": int,
        "anime_status": AnimeStatusJson,
        "type": AnimeTypeJson,
        "remote_ids": RemoteIdsJson,
        "top": TopJson,
        "blocked_in": List[str],
    },
)
VideoItemJson = TypedDict(
    "VideoItemJson",
    {
        "video_id": int,
        "data": VideoDataJson,
        "number": str,
        "date": int,
        "iframe_url": str,
        "index": int,
        "skips": SkipsJson,
        "views": int,
        "duration": int,
    },
)
GenreDetailJson = TypedDict(
    "GenreDetailJson",
    {
        "title": str,
        "id": int,
        "alias": str,
        "url": str,
        "description": str,
        "sub_genres": List[GenreShortJson],
    },
)
AnimeListResponseJson = TypedDict(
    "AnimeListResponseJson",
    {
        "response": List[AnimeItemJson],
    },
)
ScheduleResponseJson = TypedDict(
    "ScheduleResponseJson",
    {
        "response": List[ScheduleItemJson],
    },
)
VideoListResponseJson = TypedDict(
    "VideoListResponseJson",
    {
        "response": List[VideoItemJson],
    },
)
GenresDataJson = TypedDict(
    "GenresDataJson",
    {
        "genres": List[GenreJson],
        "groups": List[GenreGroupJson],
    },
)
GenresResponseJson = TypedDict(
    "GenresResponseJson",
    {
        "response": GenresDataJson,
    },
)
CatalogDataJson = TypedDict(
    "CatalogDataJson",
    {
        "genres": GenresDataJson,
        "types": List[TypeCountJson],
        "data": List[AnimeItemJson],
    },
)
CatalogResponseJson = TypedDict(
    "CatalogResponseJson",
    {
        "response": CatalogDataJson,
    },
)
GenreDetailResponseJson = TypedDict(
    "GenreDetailResponseJson",
    {
        "response": GenreDetailJson,
    },
)
TypeCountsResponseJson = TypedDict(
    "TypeCountsResponseJson",
    {
        "response": List[TypeCountJson],
    },
)
ApiErrorJson = TypedDict(
    "ApiErrorJson",
    {
        "error": str,
        "error_title": str,
        "error_code": int,
        "error_name": str,
    },
)


@dataclass(frozen=True)
class YummyAnimeApiErr200Error(Err[ApiErrorJson]):
    status: Literal[200] = 200


SearchAnimeResult = Union[Ok[AnimeListResponseJson], YummyAnimeApiErr200Error, UnknownErr, TransportErr]

AnimeByIdsResult = Union[Ok[AnimeListResponseJson], YummyAnimeApiErr200Error, UnknownErr, TransportErr]

SearchDedicatedResult = Union[Ok[AnimeListResponseJson], YummyAnimeApiErr200Error, UnknownErr, TransportErr]

ScheduleResult = Union[Ok[ScheduleResponseJson], YummyAnimeApiErr200Error, UnknownErr, TransportErr]

AnimeVideosResult = Union[Ok[VideoListResponseJson], YummyAnimeApiErr200Error, UnknownErr, TransportErr]

CatalogResult = Union[Ok[CatalogResponseJson], YummyAnimeApiErr200Error, UnknownErr, TransportErr]

ListGenresResult = Union[Ok[GenresResponseJson], YummyAnimeApiErr200Error, UnknownErr, TransportErr]

GenreBySlugResult = Union[Ok[GenreDetailResponseJson], YummyAnimeApiErr200Error, UnknownErr, TransportErr]

CountsByTypeResult = Union[Ok[TypeCountsResponseJson], YummyAnimeApiErr200Error, UnknownErr, TransportErr]

YUMMY_ANIME_API_MATCHERS: List[ErrMatcher] = [
    ErrMatcher(200, lambda _b: "error" in _b, YummyAnimeApiErr200Error),
]


class YummyAnimeApi:
    """
    YummyAnime API client (api.yani.tv).
    """

    @classmethod
    def search_anime(
        cls, client: httpx.Client, *, q: str, offset: Optional[int] = None, limit: Optional[int] = None
    ) -> SearchAnimeResult:
        """Search anime by query with pagination."""
        _params: dict = {}
        _params["q"] = q
        if offset is not None:
            _params["offset"] = offset
        if limit is not None:
            _params["limit"] = limit
        return cast(
            SearchAnimeResult,
            ssc_rest_call(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/anime",
                headers={"Accept": "application/json"},
                params=_params,
            ),
        )

    @classmethod
    async def async_search_anime(
        cls, client: httpx.AsyncClient, *, q: str, offset: Optional[int] = None, limit: Optional[int] = None
    ) -> SearchAnimeResult:
        """Search anime by query with pagination."""
        _params: dict = {}
        _params["q"] = q
        if offset is not None:
            _params["offset"] = offset
        if limit is not None:
            _params["limit"] = limit
        return cast(
            SearchAnimeResult,
            await ssc_rest_call_async(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/anime",
                headers={"Accept": "application/json"},
                params=_params,
            ),
        )

    @classmethod
    def anime_by_ids(cls, client: httpx.Client, *, ids: List[int]) -> AnimeByIdsResult:
        """Filter anime by IDs. Returns items with genres."""
        return cast(
            AnimeByIdsResult,
            ssc_rest_call(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/anime",
                headers={"Accept": "application/json"},
                params={"ids": ids},
            ),
        )

    @classmethod
    async def async_anime_by_ids(cls, client: httpx.AsyncClient, *, ids: List[int]) -> AnimeByIdsResult:
        """Filter anime by IDs. Returns items with genres."""
        return cast(
            AnimeByIdsResult,
            await ssc_rest_call_async(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/anime",
                headers={"Accept": "application/json"},
                params={"ids": ids},
            ),
        )

    @classmethod
    def search_dedicated(cls, client: httpx.Client, *, q: str) -> SearchDedicatedResult:
        """Quick search (min 3 chars). Same shape as search-anime."""
        return cast(
            SearchDedicatedResult,
            ssc_rest_call(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/search",
                headers={"Accept": "application/json"},
                params={"q": q},
            ),
        )

    @classmethod
    async def async_search_dedicated(cls, client: httpx.AsyncClient, *, q: str) -> SearchDedicatedResult:
        """Quick search (min 3 chars). Same shape as search-anime."""
        return cast(
            SearchDedicatedResult,
            await ssc_rest_call_async(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/search",
                headers={"Accept": "application/json"},
                params={"q": q},
            ),
        )

    @classmethod
    def schedule(cls, client: httpx.Client) -> ScheduleResult:
        """Current ongoing schedule."""
        return cast(
            ScheduleResult,
            ssc_rest_call(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/anime/schedule",
                headers={"Accept": "application/json"},
            ),
        )

    @classmethod
    async def async_schedule(cls, client: httpx.AsyncClient) -> ScheduleResult:
        """Current ongoing schedule."""
        return cast(
            ScheduleResult,
            await ssc_rest_call_async(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/anime/schedule",
                headers={"Accept": "application/json"},
            ),
        )

    @classmethod
    def anime_videos(cls, client: httpx.Client, *, id: int) -> AnimeVideosResult:
        """Episodes/videos for a specific anime by id."""
        return cast(
            AnimeVideosResult,
            ssc_rest_call(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                f"https://api.yani.tv/anime/{id}/videos",
                headers={"Accept": "application/json"},
            ),
        )

    @classmethod
    async def async_anime_videos(cls, client: httpx.AsyncClient, *, id: int) -> AnimeVideosResult:
        """Episodes/videos for a specific anime by id."""
        return cast(
            AnimeVideosResult,
            await ssc_rest_call_async(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                f"https://api.yani.tv/anime/{id}/videos",
                headers={"Accept": "application/json"},
            ),
        )

    @classmethod
    def catalog(cls, client: httpx.Client) -> CatalogResult:
        """Full catalog with genres, types, and anime data."""
        return cast(
            CatalogResult,
            ssc_rest_call(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/anime/catalog",
                headers={"Accept": "application/json"},
            ),
        )

    @classmethod
    async def async_catalog(cls, client: httpx.AsyncClient) -> CatalogResult:
        """Full catalog with genres, types, and anime data."""
        return cast(
            CatalogResult,
            await ssc_rest_call_async(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/anime/catalog",
                headers={"Accept": "application/json"},
            ),
        )

    @classmethod
    def list_genres(cls, client: httpx.Client) -> ListGenresResult:
        """All genres with groups."""
        return cast(
            ListGenresResult,
            ssc_rest_call(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/anime/genres",
                headers={"Accept": "application/json"},
            ),
        )

    @classmethod
    async def async_list_genres(cls, client: httpx.AsyncClient) -> ListGenresResult:
        """All genres with groups."""
        return cast(
            ListGenresResult,
            await ssc_rest_call_async(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/anime/genres",
                headers={"Accept": "application/json"},
            ),
        )

    @classmethod
    def genre_by_slug(cls, client: httpx.Client, *, slug: str) -> GenreBySlugResult:
        """Genre detail by slug (e.g. 'senen')."""
        return cast(
            GenreBySlugResult,
            ssc_rest_call(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                f"https://api.yani.tv/anime/genres/{slug}",
                headers={"Accept": "application/json"},
            ),
        )

    @classmethod
    async def async_genre_by_slug(cls, client: httpx.AsyncClient, *, slug: str) -> GenreBySlugResult:
        """Genre detail by slug (e.g. 'senen')."""
        return cast(
            GenreBySlugResult,
            await ssc_rest_call_async(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                f"https://api.yani.tv/anime/genres/{slug}",
                headers={"Accept": "application/json"},
            ),
        )

    @classmethod
    def counts_by_type(cls, client: httpx.Client) -> CountsByTypeResult:
        """Anime counts grouped by type."""
        return cast(
            CountsByTypeResult,
            ssc_rest_call(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/anime/counts/types",
                headers={"Accept": "application/json"},
            ),
        )

    @classmethod
    async def async_counts_by_type(cls, client: httpx.AsyncClient) -> CountsByTypeResult:
        """Anime counts grouped by type."""
        return cast(
            CountsByTypeResult,
            await ssc_rest_call_async(
                client,
                YUMMY_ANIME_API_MATCHERS,
                "GET",
                "https://api.yani.tv/anime/counts/types",
                headers={"Accept": "application/json"},
            ),
        )
