# autogenerated by ssc-gen. DO NOT EDIT
from lxml import html
from lxml.html import HtmlElement
from typing import TypedDict, Union
from typing_extensions import NotRequired
import json
import httpx
from .sscgen_runtime import FALLBACK_HTML_STR

from .sscgen_runtime import std_unescape_text, std_repl_map, std_re_search

DashJson = TypedDict(
    "DashJson",
    {
        "src": str,
        "type": str,
    },
)
HlsJson = TypedDict(
    "HlsJson",
    {
        "src": str,
        "type": str,
    },
)
DataParametersJson = TypedDict(
    "DataParametersJson",
    {
        "id": str,
        "error": str,
        "domain": str,
        "cdn": str,
        "counter": NotRequired[str],
        "duration": str,
        "poster": str,
        "thumbnails": str,
        "dash": NotRequired[DashJson],
        "hls": HlsJson,
        "quality": bool,
        "qualityVideo": int,
        "vast": bool,
        "country": str,
        "city": str,
        "platform": str,
        "rating": str,
        "nshowbl": bool,
        "limitRate": bool,
        "aBlocklimitRate": bool,
    },
)
PageAniboomType = TypedDict(
    "PageAniboomType",
    {
        "data_parameters": DataParametersJson,
        "hls": str,
        "dash": str,
    },
)


class PageAniboom:
    """
    
    Extract MPD and M3U8 urls
    
    NOTE: use data_parameters instead hls and dash keys for get urls
    
    Required `referer="https://animego.org/` HEADER (.me, .club?)
    
    USAGE:
        1. GET <PLAYER_LINK> (e.g. https://aniboom.one/embed/6BmMbB7MxWO?episode=1&translation=30)
        2. PARSE. If pre-unescape response before parse - css selector may not find attribute
        3. For video playing, url required next headers:
    
        - Referer="https://aniboom.one/"
        - Accept-Language="ru-RU"  # INCREASE DOWNLOAD SPEED with this static value
        - Origin="https://aniboom.one"
    ISSUES:
        - 403 Forbidden if request sent not from CIS region
        - KEYS SHOULD BE STARTED IN Title Case else hls/mpd links returns 403 error
        - Sometimes, aniboom backend missing MPD key and returns M3U8 url. Check this value before usage:
    
        https://github.com/vypivshiy/ani-cli-ru/issues/29
    
        Expected json signature (LOOK at dash.src and hls.src keys):
    
        { ...
        "dash":"{\"src\":\"https:.../abcdef.mpd\",\
        "type\":\"application\\\/dash+xml\"}",
        "hls":"{\"src\":\"https:...\\\/master_device.m3u8\",
        \"type\":\"application\\\/x-mpegURL\"}"
    
        ... }
    
        MAYBE returns this:
    
         { ...
        "dash":"{\"src\":\"https:...master_device.m3u8\",\
        "type\":\"application\\\/dash+xml\"}",
        "hls":"{\"src\":\"https:...master_device.m3u8\",
        \"type\":\"application\\\/x-mpegURL\"}"
    
        ... }
    """

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        else:
            self._doc = document
        self._expr_data = self._init_expr_data(self._doc)

    def _init_expr_data(self, v: HtmlElement) -> str:
        v1 = v.cssselect("#video[data-parameters]")[0]
        v2 = v1.get("data-parameters", "")
        return v2

    @classmethod
    def fetch(cls, client: httpx.Client, *, url_aniboom_player: str) -> "PageAniboom":
        _resp = client.request(
            "GET",
            url_aniboom_player,
            headers={
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                "Referer": "https://animego.me/",
            },
        )
        _resp.raise_for_status()
        _body = _resp.text
        return cls(_body)

    @classmethod
    async def async_fetch(cls, client: httpx.AsyncClient, *, url_aniboom_player: str) -> "PageAniboom":
        _resp = await client.request(
            "GET",
            url_aniboom_player,
            headers={
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                "Referer": "https://animego.me/",
            },
        )
        _resp.raise_for_status()
        _body = _resp.text
        return cls(_body)

    def _parse_data_parameters(self, v: HtmlElement) -> DataParametersJson:
        v1 = self._expr_data
        v2 = std_unescape_text(v1)
        v3 = json.loads(v2)
        return v3

    def _parse_hls(self, v: HtmlElement) -> str:
        v1 = self._expr_data
        v2 = std_repl_map(v1, {"\\": "", "&quot;": '"'})
        v3 = std_re_search(
            '"hls":"{"src":"(https?.*?\\.m3u8)"',
            v2,
            'aniboom_parser.kdl:117:9 re-match failed at PageAniboom.hls pattern="hls":"{"src":"(https?.*?\\.m3u8)"',
        )
        return v3

    def _parse_dash(self, v: HtmlElement) -> str:
        v1 = self._expr_data
        v2 = std_repl_map(v1, {"\\": "", "&quot;": '"'})
        v3 = std_re_search(
            '"dash":"{"src":"(https?.*?\\.(?:mpd|m3u8))"',
            v2,
            'aniboom_parser.kdl:126:9 re-match failed at PageAniboom.dash pattern="dash":"{"src":"(https?.*?\\.(?:mpd|m3u8))"',
        )
        return v3

    def parse(self) -> PageAniboomType:
        return {
            "data_parameters": self._parse_data_parameters(self._doc),
            "hls": self._parse_hls(self._doc),
            "dash": self._parse_dash(self._doc),
        }
