# autogenerated by ssc-gen. DO NOT EDIT
from lxml import html
from lxml.html import HtmlElement
from typing import List, Optional, TypedDict, Union
from dataclasses import dataclass
from typing import Literal
from typing import cast
import httpx
from .sscgen_runtime import (
    FALLBACK_HTML_STR,
    Ok,
    Err,
    UnknownErr,
    TransportErr,
    ErrMatcher,
    ssc_rest_call,
    ssc_rest_call_async,
)

PrerollJson = TypedDict(
    "PrerollJson",
    {
        "url:": str,
        "priority": int,
    },
)
VastJson = TypedDict(
    "VastJson",
    {
        "preroll": List[str],
        "prerolls": List[PrerollJson],
        "pauseroll": List[str],
        "pauserolls": List[PrerollJson],
    },
)
ItemJson = TypedDict(
    "ItemJson",
    {
        "cvhId": str,
        "name": str,
        "vkId": str,
        "voiceStudio": str,
        "voiceType": str,
        "season": int,
        "episode": int,
    },
)
CdnVideoHubResponseJson = TypedDict(
    "CdnVideoHubResponseJson",
    {
        "titleName": str,
        "isSerial": bool,
        "items": List[ItemJson],
        "trailers": Optional[str],
        "vast": VastJson,
    },
)
CdnVideoHubErrorJson = TypedDict(
    "CdnVideoHubErrorJson",
    {
        "error": str,
    },
)
VideoSourceJson = TypedDict(
    "VideoSourceJson",
    {
        "hlsUrl": str,
        "dashUrl": str,
        "mpegQhdUrl": str,
        "mpeg2kUrl": str,
        "mpeg4kUrl": str,
        "mpegHighUrl": str,
        "mpegFullHdUrl": str,
        "mpegMediumUrl": str,
        "mpegLowUrl": str,
        "mpegLowestUrl": str,
        "mpegTinyUrl": str,
    },
)
CdnVideoFromIdResponseJson = TypedDict(
    "CdnVideoFromIdResponseJson",
    {
        "unitedVideoId": int,
        "duration": int,
        "failoverHost": str,
        "thumbUrl": str,
        "sources": VideoSourceJson,
    },
)
PageParseCdnVideoDataType = TypedDict(
    "PageParseCdnVideoDataType",
    {
        "id": str,
        "data_title_id": str,
        "data_publisher_id": str,
        "ident": str,
        "data_aggregator": str,
    },
)


@dataclass(frozen=True)
class CdnVideoHubAPIErr400(Err[CdnVideoHubErrorJson]):
    status: Literal[400] = 400


GetParamsFromPageResult = Union[Ok[CdnVideoHubResponseJson], CdnVideoHubAPIErr400, UnknownErr, TransportErr]

FromVkidResult = Union[Ok[CdnVideoFromIdResponseJson], CdnVideoHubAPIErr400, UnknownErr, TransportErr]

CDN_VIDEO_HUB_API_MATCHERS: List[ErrMatcher] = [
    ErrMatcher(400, None, CdnVideoHubAPIErr400),
]


class CdnVideoHubAPI:
    """
    get required arguments from PageParseCdnVideoData structure
    """

    @classmethod
    def get_params_from_page(cls, client: httpx.Client, *, pub: str, aggr: str, id: str) -> GetParamsFromPageResult:
        return cast(
            GetParamsFromPageResult,
            ssc_rest_call(
                client,
                CDN_VIDEO_HUB_API_MATCHERS,
                "GET",
                "https://plapi.cdnvideohub.com/api/v1/player/sv/playlist",
                headers={"Accept": "application/json, text/plain, */*"},
                params={"pub": pub, "aggr": aggr, "id": id},
            ),
        )

    @classmethod
    async def async_get_params_from_page(
        cls, client: httpx.AsyncClient, *, pub: str, aggr: str, id: str
    ) -> GetParamsFromPageResult:
        return cast(
            GetParamsFromPageResult,
            await ssc_rest_call_async(
                client,
                CDN_VIDEO_HUB_API_MATCHERS,
                "GET",
                "https://plapi.cdnvideohub.com/api/v1/player/sv/playlist",
                headers={"Accept": "application/json, text/plain, */*"},
                params={"pub": pub, "aggr": aggr, "id": id},
            ),
        )

    @classmethod
    def from_vkid(cls, client: httpx.Client, *, id: str) -> FromVkidResult:
        return cast(
            FromVkidResult,
            ssc_rest_call(
                client,
                CDN_VIDEO_HUB_API_MATCHERS,
                "GET",
                f"https://plapi.cdnvideohub.com/api/v1/player/sv/video/{id}",
                headers={"Accept": "application/json, text/plain, */*"},
            ),
        )

    @classmethod
    async def async_from_vkid(cls, client: httpx.AsyncClient, *, id: str) -> FromVkidResult:
        return cast(
            FromVkidResult,
            await ssc_rest_call_async(
                client,
                CDN_VIDEO_HUB_API_MATCHERS,
                "GET",
                f"https://plapi.cdnvideohub.com/api/v1/player/sv/video/{id}",
                headers={"Accept": "application/json, text/plain, */*"},
            ),
        )


class PageParseCdnVideoData:
    """
    universal extractor cdnvideohub API params

    page should be contains <video-player> tag
    """

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        else:
            self._doc = document
        self._tag = self._init_tag(self._doc)

    def _init_tag(self, v: HtmlElement) -> HtmlElement:
        v1 = v.cssselect("video-player")[0]
        return v1

    def _parse_id(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("id", "")
        return v2

    def _parse_data_title_id(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("data-title-id", "")
        return v2

    def _parse_data_publisher_id(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("data-publisher-id", "")
        return v2

    def _parse_ident(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("ident", "")
        return v2

    def _parse_data_aggregator(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("data-aggregator", "")
        return v2

    def parse(self) -> PageParseCdnVideoDataType:
        return {
            "id": self._parse_id(self._doc),
            "data_title_id": self._parse_data_title_id(self._doc),
            "data_publisher_id": self._parse_data_publisher_id(self._doc),
            "ident": self._parse_ident(self._doc),
            "data_aggregator": self._parse_data_aggregator(self._doc),
        }
