# autogenerated by ssc-gen. DO NOT EDIT
""""""

import re
import sys
from typing import TypedDict, Dict, Union
from html import unescape as _html_unescape
from lxml import html
from lxml.html import HtmlElement

FALLBACK_HTML_STR = "<html><body></body></html>"
_RE_HEX_ENTITY = re.compile(r"&#x([0-9a-fA-F]+);")
_RE_UNICODE_ENTITY = re.compile(r"\\u([0-9a-fA-F]{4})")
_RE_BYTES_ENTITY = re.compile(r"\\x([0-9a-fA-F]{2})")
_RE_CHARS_MAP = {"\\b": "\\b", "\\f": "\\f", "\\n": "\\n", "\\r": "\\r", "\\t": "\\t"}


def repl_map(s: str, rmap: Dict[str, str]) -> str:
    for k, v in rmap.items():
        s = s.replace(k, v)
    return s


def normalize_text(text: str) -> str:
    return " ".join(text.split()) if text else ""


class _UnmatchedTableRow:
    pass


def unescape_text(text: str) -> str:
    s = _html_unescape(text)
    s = _RE_HEX_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
    s = _RE_UNICODE_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
    s = _RE_BYTES_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
    for ch, r in _RE_CHARS_MAP.items():
        s = s.replace(ch, r)
    return s


if sys.version_info >= (3, 9):

    def rm_prefix(s: str, p: str) -> str:
        return s.removeprefix(p)

    def rm_suffix(s: str, p: str) -> str:
        return s.removesuffix(p)


else:

    def rm_prefix(s: str, p: str) -> str:
        return s[len(p) :] if s.startswith(p) else s

    def rm_suffix(s: str, p: str) -> str:
        return s[: -(len(p))] if s.endswith(p) else s


UNMATCHED_TABLE_ROW = _UnmatchedTableRow()


class PageAnimegoIframeType(TypedDict):
    id: str
    data_title_id: str
    data_publisher_id: str
    ident: str
    data_aggregator: str
    is_show_voice_only: bool
    is_show_banner: bool
    episode: int
    priority_voice: str


class PageParseCdnVideoDataType(TypedDict):
    id: str
    data_title_id: str
    data_publisher_id: str
    ident: str
    data_aggregator: str


class PageAnimegoIframe:
    """

    A parser for extracting parameters for the cdnvideohub API.

    used in animego

    USAGE:

        - data_title_id for 'id=' param
        - data_publisher_id for 'pub=' param
        - data_aggregator for 'aggr=' param

    GET https://plapi.cdnvideohub.com/api/v1/player/sv/playlist?pub={data_publisher_id}&aggr={data_aggregator}&id={id}

    EXAMPLE:

        GET https://animego.me/cdn-iframe/60254/Dream%20Cast/1/1
        Referer: https://animego.me
    """

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, HtmlElement):
            self._doc = document
        elif isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        self._tag = self._init_tag(self._doc)

    def _init_tag(self, v: HtmlElement) -> HtmlElement:
        v1 = v.cssselect(".player-cvh > video-player")[0]
        return v1

    def _parse_id(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("id", "")
        return v2

    def _parse_data_title_id(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("data-title-id", "")
        return v2

    def _parse_data_publisher_id(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("data-publisher-id", "")
        return v2

    def _parse_ident(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("ident", "")
        return v2

    def _parse_data_aggregator(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("data-aggregator", "")
        return v2

    def _parse_is_show_voice_only(self, v: HtmlElement) -> bool:
        try:
            v1 = self._tag
            v2 = v1.get("is-show-voice-only", "")
            i = v2
            assert i == "true"
            v3 = v2
            v4 = bool(v3)
        except Exception:
            return False
        return v4

    def _parse_is_show_banner(self, v: HtmlElement) -> bool:
        try:
            v1 = self._tag
            v2 = v1.get("is_show_banner", "")
            i = v2
            assert i == "true"
            v3 = v2
            v4 = bool(v3)
        except Exception:
            return False
        return v4

    def _parse_episode(self, v: HtmlElement) -> int:
        v1 = self._tag
        v2 = v1.get("episode", "")
        v3 = int(v2)
        return v3

    def _parse_priority_voice(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("priority-voice", "")
        return v2

    def parse(self) -> PageAnimegoIframeType:
        return {
            "id": self._parse_id(self._doc),
            "data_title_id": self._parse_data_title_id(self._doc),
            "data_publisher_id": self._parse_data_publisher_id(self._doc),
            "ident": self._parse_ident(self._doc),
            "data_aggregator": self._parse_data_aggregator(self._doc),
            "is_show_voice_only": self._parse_is_show_voice_only(self._doc),
            "is_show_banner": self._parse_is_show_banner(self._doc),
            "episode": self._parse_episode(self._doc),
            "priority_voice": self._parse_priority_voice(self._doc),
        }


class PageParseCdnVideoData:
    """

    universal extractor cdnvideohub API params

    page should be contains <video-player> tag

    """

    def __init__(self, document: Union[str, HtmlElement]):
        if isinstance(document, HtmlElement):
            self._doc = document
        elif isinstance(document, str):
            self._doc = html.fromstring(document.strip() or FALLBACK_HTML_STR)
        self._tag = self._init_tag(self._doc)

    def _init_tag(self, v: HtmlElement) -> HtmlElement:
        v1 = v.cssselect("video-player")[0]
        return v1

    def _parse_id(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("id", "")
        return v2

    def _parse_data_title_id(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("data-title-id", "")
        return v2

    def _parse_data_publisher_id(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("data-publisher-id", "")
        return v2

    def _parse_ident(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("ident", "")
        return v2

    def _parse_data_aggregator(self, v: HtmlElement) -> str:
        v1 = self._tag
        v2 = v1.get("data-aggregator", "")
        return v2

    def parse(self) -> PageParseCdnVideoDataType:
        return {
            "id": self._parse_id(self._doc),
            "data_title_id": self._parse_data_title_id(self._doc),
            "data_publisher_id": self._parse_data_publisher_id(self._doc),
            "ident": self._parse_ident(self._doc),
            "data_aggregator": self._parse_data_aggregator(self._doc),
        }
