# autogenerated runtime helpers — do not edit
import re
import sys
from typing import Dict
from html import unescape as ssc_html_unescape
from dataclasses import dataclass, field
from typing import Any, Generic, Literal, Mapping, TypeVar


FALLBACK_HTML_STR = "<html><body></body></html>"

_RE_HEX_ENTITY = re.compile(r"&#x([0-9a-fA-F]+);")
_RE_UNICODE_ENTITY = re.compile(r"\\u([0-9a-fA-F]{4})")
_RE_BYTES_ENTITY = re.compile(r"\\x([0-9a-fA-F]{2})")
_RE_CHARS_MAP = {"\b": "\b", "\f": "\f", "\n": "\n", "\r": "\r", "\t": "\t"}


def repl_map(s: str, rmap: Dict[str, str]) -> str:
    for k, v in rmap.items():
        s = s.replace(k, v)
    return s


def normalize_text(text: str) -> str:
    return " ".join(text.split()) if text else ""


class _UnmatchedTableRow:
    pass


def unescape_text(text: str) -> str:
    s = ssc_html_unescape(text)
    s = _RE_HEX_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
    s = _RE_UNICODE_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
    s = _RE_BYTES_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
    for ch, r in _RE_CHARS_MAP.items():
        s = s.replace(ch, r)
    return s


if sys.version_info >= (3, 9):

    def rm_prefix(s: str, p: str) -> str:
        return s.removeprefix(p)

    def rm_suffix(s: str, p: str) -> str:
        return s.removesuffix(p)

else:

    def rm_prefix(s: str, p: str) -> str:
        return s[len(p) :] if s.startswith(p) else s

    def rm_suffix(s: str, p: str) -> str:
        return s[: -(len(p))] if s.endswith(p) else s


UNMATCHED_TABLE_ROW = _UnmatchedTableRow()

_T = TypeVar("_T")
_E = TypeVar("_E")


@dataclass(frozen=True)
class Ok(Generic[_T]):
    status: int = 0
    headers: Mapping[str, str] = field(default_factory=dict)
    value: _T = None  # type: ignore[assignment]
    is_ok: Literal[True] = True


@dataclass(frozen=True)
class Err(Generic[_E]):
    status: int = 0
    headers: Mapping[str, str] = field(default_factory=dict)
    value: _E = None  # type: ignore[assignment]
    is_ok: Literal[False] = False


@dataclass(frozen=True)
class UnknownErr(Err[Any]):
    pass


@dataclass(frozen=True)
class TransportErr(Err[None]):
    status: Literal[0] = 0
    cause: str = ""
    value: None = None
    headers: Mapping[str, str] = field(default_factory=dict)


def ssc_parse_response(_resp):
    _status = _resp.status_code
    _headers = {k.lower(): v for k, v in _resp.headers.items()}
    try:
        _body = _resp.json()
    except Exception:
        _body = None
    return _status, _headers, _body
